import { ClassData } from './types';
import { Class, Alignment, FighterSpecialization, MagicMajor } from './enums';

export const classes: Record<Class, ClassData> = {
  [Class.FIGHTER]: {
    name: Class.FIGHTER,
    title: 'Fighter',
    slug: 'fighter',
    description: 'Best all around fighters, little magic ability.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [
      { label: 'specialization', url: '/help/specialization-specialize' },
    ],
    consumables: [],
    weapons: [
      { name: 'axe', level: 1 },
      { name: 'dagger', level: 1 },
      { name: 'flail', level: 1 },
      { name: 'mace', level: 1 },
      { name: 'polearm', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
      { name: 'bow', level: 1 },
      { name: 'crossbow', level: 1 },
    ],
    basicSkills: [
      { name: 'shield block', level: 1, url: '/help/shield-block' },
      { name: 'enhanced damage', level: 1, url: '/help/enhanced-damage' },
      { name: 'rescue', level: 1, url: '/help/rescue' },
      { name: 'parry', level: 1, url: '/help/parry' },
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'dirt kicking', level: 2, url: '/help/dirt-dirt-kicking' },
      { name: 'hand to hand', level: 3, url: '/help/hand-to-hand' },
      { name: 'kick', level: 3, url: '/help/kick' },
      { name: 'second attack', level: 4, url: '/help/second-attack' },
      { name: 'fast healing', level: 5, url: '/help/fast-healing' },
      { name: 'trip', level: 6, url: '/help/trip' },
      { name: 'feint', level: 7, url: '/help/feint' },
      { name: 'bandage', level: 8, url: '/help/bandage' },
      { name: 'warcry', level: 9, url: '/help/warcry' },
      { name: 'disarm', level: 9, url: '/help/disarm' },
      { name: 'dual wield', level: 10, url: '/help/dual-dual-wield' },
      { name: 'dodge', level: 10, url: '/help/dodge' },
      { name: 'riding', level: 10, url: '/help/mount-ride-dismount-riding' },
      { name: 'bash', level: 11, url: '/help/bash' },
      { name: 'third attack', level: 11, url: '/help/third-attack-fourth-attack' },
      { name: 'berserk', level: 12, url: '/help/berserk' },
      { name: 'haggle', level: 12, url: '/help/haggle-haggling' },
      { name: 'meditation', level: 12, url: '/help/meditation' },
      { name: 'shield cleave', level: 13, url: '/help/shield-cleave' },
      { name: 'stance', level: 13, url: '/help/stance-stances-relax' },
      { name: 'lunge', level: 14, url: '/help/lunge' },
      { name: 'trophy', level: 14, url: '/help/trophy' },
      { name: 'crush', level: 15, url: '/help/crush' },
      { name: 'lore', level: 16, url: '/help/lore' },
      { name: 'offhand disarm', level: 16, url: '/help/offhand-disarm' },
      { name: 'mounted fighting', level: 16, url: '/help/mounted-fighting' },
      { name: 'recovery', level: 17, url: '/help/recovery' },
      { name: 'toughen', level: 20, url: '/help/toughen' },
      { name: 'warrior spirit', level: 21, url: '/help/warrior-spirit' },
      { name: 'fourth attack', level: 23, url: '/help/third-attack-fourth-attack' },
      { name: 'adrenalin rush', level: 25, url: '/help/adrenalin-rush' },
    ],
    specChoices: 3,
    specAllowed: [
      FighterSpecialization.SWORD,
      FighterSpecialization.DAGGER,
      FighterSpecialization.WHIP_FLAIL,
      FighterSpecialization.MACE,
      FighterSpecialization.AXE,
      FighterSpecialization.STAFF,
      FighterSpecialization.SPEAR,
      FighterSpecialization.HAND_TO_HAND,
      FighterSpecialization.RANGED,
      FighterSpecialization.SHIELD,
    ],
    specs: [
      {
        id: FighterSpecialization.SWORD,
        skills: [
          { name: 'flurry', level: 29, url: '/help/flurry' },
          { name: 'flourentine', level: 18, url: '/help/flourentine' },
          { name: 'riposte', level: 21, url: '/help/riposte' },
          { name: 'cross slice', level: 22, url: '/help/cross-slice-crossslice' },
        ],
      },
      {
        id: FighterSpecialization.DAGGER,
        skills: [
          { name: 'undercut', level: 19, url: '/help/undercut' },
          { name: 'bleed', level: 14, url: '/help/bleed' },
          { name: 'restrike', level: 24, url: '/help/restrike' },
        ],
      },
      {
        id: FighterSpecialization.WHIP_FLAIL,
        skills: [
          { name: 'flog', level: 16, url: '/help/flog-flogging' },
          { name: 'strip weapon', level: 16, url: '/help/strip-weapon' },
          { name: 'choke', level: 21, url: '/help/choke' },
          { name: 'lash', level: 11, url: '/help/lash' },
          { name: 'pull', level: 19, url: '/help/pull' },
          { name: 'eyejab', level: 13, url: '/help/eyejab' },
        ],
      },
      {
        id: FighterSpecialization.MACE,
        skills: [
          { name: 'boneshatter', level: 17, url: '/help/boneshatter' },
          { name: 'backhand', level: 15, url: '/help/backhand' },
          { name: 'drumming maces', level: 26, url: '/help/drumming-maces-drum' },
        ],
      },
      {
        id: FighterSpecialization.AXE,
        skills: [
          { name: 'pincer', level: 21, url: '/help/pincer' },
          { name: 'cleave', level: 26, url: '/help/cleave' },
          { name: 'chop', level: 14, url: '/help/chop' },
          { name: 'concussion strike', level: 23, url: '/help/concussion-strike-concussion' },
          { name: 'wrist chop', level: 26, url: '/help/wrist-chop-wristchop' },
          { name: 'meatgrinder', level: 28, url: '/help/meatgrinder' },
        ],
      },
      {
        id: FighterSpecialization.STAFF,
        skills: [
          { name: 'overhead', level: 20, url: '/help/overhead' },
          { name: 'pugil', level: 10, url: '/help/pugil' },
          { name: 'leg sweep', level: 16, url: '/help/leg-sweep-legsweep' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
        ],
      },
      {
        id: FighterSpecialization.SPEAR,
        skills: [
          { name: 'charge set', level: 22, url: '/help/charge-set' },
          { name: 'impale', level: 26, url: '/help/impale' },
          { name: 'jab', level: 16, url: '/help/jab' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
          { name: 'harpoon', level: 31, url: '/help/harpoon' },
        ],
      },
      {
        id: FighterSpecialization.HAND_TO_HAND,
        skills: [
          { name: 'iron strike', level: 11, url: '/help/iron-strike-ironstrike' },
          { name: 'throw', level: 16, url: '/help/throw' },
          { name: 'leaping strike', level: 20, url: '/help/leaping-strike' },
          { name: 'ground control', level: 18, url: '/help/ground-control' },
          { name: 'hand block', level: 12, url: '/help/hand-block' },
          { name: 'grapple', level: 10, url: '/help/grapple-grappling' },
        ],
      },
      {
        id: FighterSpecialization.RANGED,
        skills: [
          { name: 'accuracy', level: 11, url: '/help/accuracy' },
          { name: 'quick shot', level: 15, url: '/help/quick-shot-quickshot' },
          { name: 'aimed shot', level: 19, url: '/help/aimed-shot' },
          { name: 'volley', level: 26, url: '/help/volley' },
        ],
      },
      {
        id: FighterSpecialization.SHIELD,
        skills: [
          { name: 'shield mastery', level: 24, url: '/help/shield-mastery' },
          { name: 'shield bash', level: 21, url: '/help/shield-bash' },
          { name: 'porcupine stance', level: 16, url: '/help/porcupine-stance' },
        ],
      },
    ],
  },

  [Class.KNIGHT]: {
    name: Class.KNIGHT,
    title: 'Knight',
    slug: 'knight',
    description: 'Seekers of full knighthood.',
    features: [],
    xpPenalty: 20,
    allowedAlignments: [Alignment.GOOD],
    reference: [],
  },

  [Class.RANGER]: {
    name: Class.RANGER,
    title: 'Ranger',
    slug: 'ranger',
    description: 'Forest warriors, learned in woodlore and survival.',
    features: [],
    xpPenalty: 10,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL],
    reference: [
      { label: 'specialization', url: '/help/specialization-specialize' },
    ],
    weapons: [
      { name: 'axe', level: 1 },
      { name: 'dagger', level: 1 },
      { name: 'flail', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
      { name: 'bow', level: 1 },
      { name: 'crossbow', level: 1 },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'bash', level: 2, url: '/help/bash' },
      { name: 'dirt kicking', level: 2, url: '/help/dirt-dirt-kicking' },
      { name: 'quiet movement', level: 3, url: '/help/quiet-movement' },
      { name: 'parry', level: 3, url: '/help/parry' },
      { name: 'butcher', level: 4, url: '/help/butcher' },
      { name: 'acute vision', level: 5, url: '/help/camouflage-acute-vision' },
      { name: 'pathfinding', level: 5 },
      { name: 'hand to hand', level: 6, url: '/help/hand-to-hand' },
      { name: 'second attack', level: 7, url: '/help/second-attack' },
      { name: 'riding', level: 7, url: '/help/mount-ride-dismount-riding' },
      { name: 'camouflage', level: 8, url: '/help/camouflage-acute-vision' },
      { name: 'herb', level: 8, url: '/help/herbs-curative-herbs' },
      { name: 'enhanced damage', level: 9, url: '/help/enhanced-damage' },
      { name: 'meditation', level: 9, url: '/help/meditation' },
      { name: 'find water', level: 10, url: '/help/find-water' },
      { name: 'ambush', level: 10, url: '/help/ambush' },
      { name: 'fast healing', level: 11, url: '/help/fast-healing' },
      { name: 'skin', level: 11 },
      { name: 'dodge', level: 12, url: '/help/dodge' },
      { name: 'snare', level: 12, url: '/help/snare' },
      { name: 'mounted fighting', level: 12, url: '/help/mounted-fighting' },
      { name: 'lore', level: 13, url: '/help/lore' },
      { name: 'dual wield', level: 13, url: '/help/dual-dual-wield' },
      { name: 'ranger ammo', level: 13, url: '/help/ranger-ammo-rangerammo' },
      { name: 'protection heat cold', level: 14, url: '/help/protection-heat-cold' },
      { name: 'camp', level: 14, url: '/help/camp' },
      { name: 'stance', level: 14, url: '/help/stance-stances-relax' },
      { name: 'shield block', level: 15, url: '/help/shield-block' },
      { name: 'curative herbs', level: 15, url: '/help/herbs-curative-herbs' },
      { name: 'third attack', level: 16, url: '/help/third-attack-fourth-attack' },
      { name: 'barkskin', level: 17, url: '/help/barkskin' },
      { name: 'flank', level: 17, url: '/help/flanking' },
      { name: 'animal call', level: 18, url: '/help/animal-call' },
      { name: 'ranger staff', level: 19, url: '/help/ranger-staff' },
      { name: 'moving ambush', level: 20, url: '/help/moving-ambush' },
      { name: 'wilderness familiarity', level: 21, url: '/help/wilderness-familiarity' },
      { name: 'tailored skins', level: 22, url: '/help/tailored-skins-tailor-skins' },
      { name: 'creep', level: 23, url: '/help/creep' },
      { name: 'hunt', level: 25, url: '/help/hunt' },
      { name: 'forest guardianship', level: 26, url: '/help/forest-guardianship-guardianship' },
      { name: 'warrior spirit', level: 26, url: '/help/warrior-spirit' },
    ],
    specChoices: 2,
    specAllowed: [
      FighterSpecialization.WHIP_FLAIL,
      FighterSpecialization.STAFF,
      FighterSpecialization.RANGED,
      FighterSpecialization.AXE,
      FighterSpecialization.HAND_TO_HAND,
      FighterSpecialization.SPEAR,
    ],
    specs: [
      {
        id: FighterSpecialization.STAFF,
        skills: [
          { name: 'overhead', level: 20, url: '/help/overhead' },
          { name: 'pugil', level: 10, url: '/help/pugil' },
          { name: 'leg sweep', level: 16, url: '/help/leg-sweep-legsweep' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
        ],
      },
      {
        id: FighterSpecialization.RANGED,
        skills: [
          { name: 'accuracy', level: 11, url: '/help/accuracy' },
          { name: 'quick shot', level: 15, url: '/help/quick-shot-quickshot' },
          { name: 'aimed shot', level: 19, url: '/help/aimed-shot' },
          { name: 'volley', level: 26, url: '/help/volley' },
        ],
      },
      {
        id: FighterSpecialization.AXE,
        skills: [
          { name: 'pincer', level: 21, url: '/help/pincer' },
          { name: 'cleave', level: 26, url: '/help/cleave' },
          { name: 'chop', level: 14, url: '/help/chop' },
          { name: 'concussion strike', level: 23, url: '/help/concussion-strike-concussion' },
          { name: 'wrist chop', level: 26, url: '/help/wrist-chop-wristchop' },
          { name: 'meatgrinder', level: 28, url: '/help/meatgrinder' },
        ],
      },
      {
        id: FighterSpecialization.SPEAR,
        skills: [
          { name: 'charge set', level: 22, url: '/help/charge-set' },
          { name: 'impale', level: 26, url: '/help/impale' },
          { name: 'jab', level: 16, url: '/help/jab' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
          { name: 'harpoon', level: 31, url: '/help/harpoon' },
        ],
      },
      {
        id: FighterSpecialization.WHIP_FLAIL,
        skills: [
          { name: 'flog', level: 16, url: '/help/flog-flogging' },
          { name: 'strip weapon', level: 16, url: '/help/strip-weapon' },
          { name: 'choke', level: 21, url: '/help/choke' },
          { name: 'lash', level: 11, url: '/help/lash' },
          { name: 'pull', level: 19, url: '/help/pull' },
          { name: 'eyejab', level: 13, url: '/help/eyejab' },
        ],
      },
      {
        id: FighterSpecialization.HAND_TO_HAND,
        skills: [
          { name: 'iron strike', level: 11, url: '/help/iron-strike-ironstrike' },
          { name: 'throw', level: 16, url: '/help/throw' },
          { name: 'leaping strike', level: 20, url: '/help/leaping-strike' },
          { name: 'ground control', level: 18, url: '/help/ground-control' },
          { name: 'hand block', level: 12, url: '/help/hand-block' },
          { name: 'grapple', level: 10, url: '/help/grapple-grappling' },
        ],
      },
    ],
  },
  [Class.CLERIC]: {
    name: Class.CLERIC,
    title: 'Cleric',
    slug: 'cleric',
    description: 'Followers of the Gods.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [{ label: 'worship', url: '/help/worship' }],
  },

  [Class.DRUID]: {
    name: Class.DRUID,
    title: 'Druid',
    slug: 'druid',
    description: 'Disciples of natural magic and control.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL],
    reference: [{ label: 'kinship', url: '/help/animal-kinship-kinship' }],
  },

  [Class.THIEF]: {
    name: Class.THIEF,
    title: 'Thief',
    slug: 'thief',
    description: "The skilled stealer of other people's belongings.",
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [],
  },

  [Class.ASSASSIN]: {
    name: Class.ASSASSIN,
    title: 'Assassin',
    slug: 'assassin',
    description: 'Specialists in stealth and unarmed killing.',
    features: [],
    xpPenalty: 15,
    allowedAlignments: [Alignment.GOOD, Alignment.EVIL],
    reference: [{ label: 'wayfollow', url: '/help/wayfollow-waypath' }],
  },

  [Class.TRANSMUTER]: {
    name: Class.TRANSMUTER,
    title: 'Transmuter',
    slug: 'transmuter',
    description: 'Specialist mages who are masters of alteration magic.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [
      { label: 'magicmajor', url: '/help/magicmajor' },
      { label: 'forms', url: '/help/forms' },
    ],
    weapons: [
      { name: 'dagger', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
    ],
    consumables: [
      { name: 'scrolls', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'staves', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'wands', level: 1, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'meditation', level: 4, url: '/help/meditation' },
      { name: 'haggle', level: 6, url: '/help/haggle' },
      { name: 'trance', level: 8, url: '/help/trance' },
      { name: 'fast healing', level: 10, url: '/help/fast-healing' },
      { name: 'parry', level: 11, url: '/help/parry' },
      { name: 'riding', level: 12, url: '/help/mount-ride-dismount-riding' },
      { name: 'mounted spellcasting', level: 14, url: '/help/mounted-spellcasting' },
      { name: 'hand to hand', level: 16, url: '/help/hand-to-hand' },
      { name: 'second attack', level: 19, url: '/help/second-attack' },
      { name: 'survival instincts', level: 20, url: '/help/survival-instincts-instincts' },
    ],
    basicSpells: [
      { name: 'armor', level: 1, url: '/help/armor' },
      { name: 'read magic', level: 1, url: '/help/read-magic' },
      { name: 'detect magic', level: 1, url: '/help/detect-magic' },
      { name: 'magic missile', level: 1, url: '/help/magic-missile' },
      { name: 'ventriloquate', level: 1, url: '/help/ventriloquate' },
      { name: 'invisibility', level: 3, url: '/help/invisibility' },
      { name: 'detect invis', level: 4, url: '/help/detect-invisibility' },
      { name: 'faerie fire', level: 5, url: '/help/faerie-fire' },
      { name: 'giant strength', level: 5, url: '/help/giant-strength' },
      { name: 'infravision', level: 6, url: '/help/infravision' },
      { name: 'shield', level: 6, url: '/help/shield' },
      { name: 'fly', level: 7, url: '/help/fly' },
      { name: 'enlarge', level: 7, url: '/help/enlarge-shrink' },
      { name: 'dispel magic', level: 8, url: '/help/dispel-magic' },
      { name: 'protective shield', level: 9, url: '/help/protective-shield' },
      { name: 'shrink', level: 9, url: '/help/enlarge-shrink' },
      { name: 'identify', level: 10, url: '/help/identify' },
      { name: 'locate object', level: 10, url: '/help/locate-object' },
      { name: 'blink', level: 10, url: '/help/blink' },
      { name: 'haste', level: 11, url: '/help/haste' },
      { name: 'teleport', level: 11, url: '/help/teleport' },
      { name: 'pass door', level: 12, url: '/help/pass-door' },
      { name: 'stoneskin', level: 12, url: '/help/ironskin-stoneskin' },
      { name: 'trace teleport', level: 13, url: '/help/trace-teleport' },
      { name: 'faerie fog', level: 14, url: '/help/faerie-fog' },
      { name: 'slow', level: 14, url: '/help/slow' },
      { name: 'dimension door', level: 14, url: '/help/dimension-door' },
      { name: 'cancellation', level: 15, url: '/help/cancellation' },
      { name: 'shapeshift', level: 16, url: '/help/shapeshift' },
      { name: 'drain', level: 16, url: '/help/drain' },
      { name: 'crystalbrittle', level: 17, url: '/help/crystalbrittle' },
      { name: 'word of recall', level: 19, url: '/help/word-of-recall' },
      { name: 'eldritch shield', level: 21, url: '/help/eldritch-shield' },
      { name: 'ironskin', level: 22, url: '/help/ironskin-stoneskin' },
      { name: 'soften', level: 23, url: '/help/soften' },
      { name: 'duo dimension', level: 24, url: '/help/duo-dimension-duo' },
      { name: 'mana shield', level: 24, url: '/help/mana-shield' },
    ],
    magicMajorChoices: [
      MagicMajor.ABJURATION,
      MagicMajor.ALTERATION,
    ],
  },

  [Class.INVOKER]: {
    name: Class.INVOKER,
    title: 'Invoker',
    slug: 'invoker',
    description: 'Specialist mages who are masters of energy manipulation.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [],
  },

  [Class.NECROMANCER]: {
    name: Class.NECROMANCER,
    title: 'Necromancer',
    slug: 'necromancer',
    description: 'Specialist mages who practice the black magics.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.EVIL],
    reference: [],
  },

  [Class.OUTCAST]: {
    name: Class.OUTCAST,
    title: 'Outcast',
    slug: 'outcast',
    description:
      'Knight outcasts who turn on good and follow the black magics.',
    features: [],
    xpPenalty: 15,
    allowedAlignments: [Alignment.EVIL],
    reference: [],
  },
};

// Helper function to get class by name
export function getClass(name: Class | string): ClassData | undefined {
  return classes[name as Class];
}

// Helper function to get class by slug
export function getClassBySlug(slug: string): ClassData | undefined {
  return Object.values(classes).find(cls => cls.slug === slug);
}

// Helper function to get all classes
export function getAllClasses(): ClassData[] {
  return Object.values(classes);
}

// Helper function to get classes by alignment
export function getClassesByAlignment(alignment: Alignment): ClassData[] {
  return Object.values(classes).filter(cls =>
    cls.allowedAlignments.includes(alignment)
  );
}
