import { ClassData } from './types';
import { Class, Alignment, Specs } from './enums';

export const classes: Record<Class, ClassData> = {
  [Class.FIGHTER]: {
    name: Class.FIGHTER,
    title: 'Fighter',
    slug: 'fighter',
    description: 'Best all around fighters, little magic ability.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [
      { label: 'specialization', url: '/help/specialization-specialize' },
    ],
    consumables: [],
    weapons: [
      { name: 'axe', level: 1 },
      { name: 'dagger', level: 1 },
      { name: 'flail', level: 1 },
      { name: 'mace', level: 1 },
      { name: 'polearm', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
      { name: 'bow', level: 1 },
      { name: 'crossbow', level: 1 },
    ],
    basicSkills: [
      { name: 'shield block', level: 1, url: '/help/shield-block' },
      { name: 'enhanced damage', level: 1, url: '/help/enhanced-damage' },
      { name: 'rescue', level: 1, url: '/help/rescue' },
      { name: 'parry', level: 1, url: '/help/parry' },
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'dirt kicking', level: 2, url: '/help/dirt-dirt-kicking' },
      { name: 'hand to hand', level: 3, url: '/help/hand-to-hand' },
      { name: 'kick', level: 3, url: '/help/kick' },
      { name: 'second attack', level: 4, url: '/help/second-attack' },
      { name: 'fast healing', level: 5, url: '/help/fast-healing' },
      { name: 'trip', level: 6, url: '/help/trip' },
      { name: 'feint', level: 7, url: '/help/feint' },
      { name: 'bandage', level: 8, url: '/help/bandage' },
      { name: 'warcry', level: 9, url: '/help/warcry' },
      { name: 'disarm', level: 9, url: '/help/disarm' },
      { name: 'dual wield', level: 10, url: '/help/dual-dual-wield' },
      { name: 'dodge', level: 10, url: '/help/dodge' },
      { name: 'riding', level: 10, url: '/help/mount-ride-dismount-riding' },
      { name: 'bash', level: 11, url: '/help/bash' },
      {
        name: 'third attack',
        level: 11,
        url: '/help/third-attack-fourth-attack',
      },
      { name: 'berserk', level: 12, url: '/help/berserk' },
      { name: 'haggle', level: 12, url: '/help/haggle-haggling' },
      { name: 'meditation', level: 12, url: '/help/meditation' },
      { name: 'shield cleave', level: 13, url: '/help/shield-cleave' },
      { name: 'stance', level: 13, url: '/help/stance-stances-relax' },
      { name: 'lunge', level: 14, url: '/help/lunge' },
      { name: 'trophy', level: 14, url: '/help/trophy' },
      { name: 'crush', level: 15, url: '/help/crush' },
      { name: 'lore', level: 16, url: '/help/lore' },
      { name: 'offhand disarm', level: 16, url: '/help/offhand-disarm' },
      { name: 'mounted fighting', level: 16, url: '/help/mounted-fighting' },
      { name: 'recovery', level: 17, url: '/help/recovery' },
      { name: 'toughen', level: 20, url: '/help/toughen' },
      { name: 'warrior spirit', level: 21, url: '/help/warrior-spirit' },
      {
        name: 'fourth attack',
        level: 23,
        url: '/help/third-attack-fourth-attack',
      },
      { name: 'adrenalin rush', level: 25, url: '/help/adrenalin-rush' },
    ],
    specChoices: 3,
    specAllowed: [
      Specs.SWORD,
      Specs.DAGGER,
      Specs.WHIP_FLAIL,
      Specs.MACE,
      Specs.AXE,
      Specs.STAFF,
      Specs.SPEAR,
      Specs.HAND_TO_HAND,
      Specs.RANGED,
      Specs.SHIELD,
    ],
    specSkills: [
      {
        id: Specs.SWORD,
        skills: [
          { name: 'flurry', level: 29, url: '/help/flurry' },
          { name: 'flourentine', level: 18, url: '/help/flourentine' },
          { name: 'riposte', level: 21, url: '/help/riposte' },
          {
            name: 'cross slice',
            level: 22,
            url: '/help/cross-slice-crossslice',
          },
        ],
      },
      {
        id: Specs.DAGGER,
        skills: [
          { name: 'undercut', level: 19, url: '/help/undercut' },
          { name: 'bleed', level: 14, url: '/help/bleed' },
          { name: 'restrike', level: 24, url: '/help/restrike' },
        ],
      },
      {
        id: Specs.WHIP_FLAIL,
        skills: [
          { name: 'flog', level: 16, url: '/help/flog-flogging' },
          { name: 'strip weapon', level: 16, url: '/help/strip-weapon' },
          { name: 'choke', level: 21, url: '/help/choke' },
          { name: 'lash', level: 11, url: '/help/lash' },
          { name: 'pull', level: 19, url: '/help/pull' },
          { name: 'eyejab', level: 13, url: '/help/eyejab' },
        ],
      },
      {
        id: Specs.MACE,
        skills: [
          { name: 'boneshatter', level: 17, url: '/help/boneshatter' },
          { name: 'backhand', level: 15, url: '/help/backhand' },
          {
            name: 'drumming maces',
            level: 26,
            url: '/help/drumming-maces-drum',
          },
        ],
      },
      {
        id: Specs.AXE,
        skills: [
          { name: 'pincer', level: 21, url: '/help/pincer' },
          { name: 'cleave', level: 26, url: '/help/cleave' },
          { name: 'chop', level: 14, url: '/help/chop' },
          {
            name: 'concussion strike',
            level: 23,
            url: '/help/concussion-strike-concussion',
          },
          { name: 'wrist chop', level: 26, url: '/help/wrist-chop-wristchop' },
          { name: 'meatgrinder', level: 28, url: '/help/meatgrinder' },
        ],
      },
      {
        id: Specs.STAFF,
        skills: [
          { name: 'overhead', level: 20, url: '/help/overhead' },
          { name: 'pugil', level: 10, url: '/help/pugil' },
          { name: 'leg sweep', level: 16, url: '/help/leg-sweep-legsweep' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
        ],
      },
      {
        id: Specs.SPEAR,
        skills: [
          { name: 'charge set', level: 22, url: '/help/charge-set' },
          { name: 'impale', level: 26, url: '/help/impale' },
          { name: 'jab', level: 16, url: '/help/jab' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
          { name: 'harpoon', level: 31, url: '/help/harpoon' },
        ],
      },
      {
        id: Specs.HAND_TO_HAND,
        skills: [
          {
            name: 'iron strike',
            level: 11,
            url: '/help/iron-strike-ironstrike',
          },
          { name: 'throw', level: 16, url: '/help/throw' },
          { name: 'leaping strike', level: 20, url: '/help/leaping-strike' },
          { name: 'ground control', level: 18, url: '/help/ground-control' },
          { name: 'hand block', level: 12, url: '/help/hand-block' },
          { name: 'grapple', level: 10, url: '/help/grapple-grappling' },
        ],
      },
      {
        id: Specs.RANGED,
        skills: [
          { name: 'accuracy', level: 11, url: '/help/accuracy' },
          { name: 'quick shot', level: 15, url: '/help/quick-shot-quickshot' },
          { name: 'aimed shot', level: 19, url: '/help/aimed-shot' },
          { name: 'volley', level: 26, url: '/help/volley' },
        ],
      },
      {
        id: Specs.SHIELD,
        skills: [
          { name: 'shield mastery', level: 24, url: '/help/shield-mastery' },
          { name: 'shield bash', level: 21, url: '/help/shield-bash' },
          {
            name: 'porcupine stance',
            level: 16,
            url: '/help/porcupine-stance',
          },
        ],
      },
    ],
  },

  [Class.KNIGHT]: {
    name: Class.KNIGHT,
    title: 'Knight',
    slug: 'knight',
    description: 'Seekers of full knighthood.',
    features: [],
    xpPenalty: 20,
    allowedAlignments: [Alignment.GOOD],
    reference: [],
    weapons: [
      { name: 'axe', level: 1 },
      { name: 'mace', level: 1 },
      { name: 'polearm', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'staff', level: 1 },
      { name: 'bow', level: 1 },
      { name: 'crossbow', level: 1 },
    ],
    consumables: [
      { name: 'scrolls', level: 2, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'shield block', level: 3, url: '/help/shield-block' },
      { name: 'kick', level: 3, url: '/help/kick' },
      { name: 'rescue', level: 5, url: '/help/rescue' },
      { name: 'parry', level: 5, url: '/help/parry' },
      { name: 'enhanced damage', level: 6, url: '/help/enhanced-damage' },
      { name: 'hand to hand', level: 6, url: '/help/hand-to-hand' },
      { name: 'fast healing', level: 6, url: '/help/fast-healing' },
      { name: 'meditation', level: 7, url: '/help/meditation' },
      { name: 'second attack', level: 8, url: '/help/second-attack' },
      { name: 'riding', level: 8, url: '/help/mount-ride-dismount-riding' },
      { name: 'bash', level: 9, url: '/help/bash' },
      { name: 'pugil', level: 10, url: '/help/pugil' },
      { name: 'lore', level: 11, url: '/help/lore' },
      { name: 'disarm', level: 12, url: '/help/disarm' },
      { name: 'dual wield', level: 14, url: '/help/dual-dual-wield' },
      { name: 'lunge', level: 14, url: '/help/lunge' },
      { name: 'mounted fighting', level: 14, url: '/help/mounted-fighting' },
      { name: 'shield cleave', level: 15, url: '/help/shield-cleave' },
      { name: 'stance', level: 15, url: '/help/stance-stances-relax' },
      { name: 'leadership', level: 15, url: '/help/leadership' },
      {
        name: 'third attack',
        level: 16,
        url: '/help/third-attack-fourth-attack',
      },
      { name: 'ceremonial burial', level: 17, url: '/help/ceremonial-burial' },
      { name: 'stand off', level: 17, url: '/help/stand-off' },
      { name: 'flank', level: 18, url: '/help/flanking' },
      { name: 'laying hands', level: 19, url: '/help/laying-hands' },
      { name: 'righteous warfare', level: 20, url: '/help/righteous-warfare' },
      { name: 'cross block', level: 20, url: '/help/cross-block' },
      { name: 'spike', level: 21, url: '/help/spike' },
      { name: 'riposte', level: 21, url: '/help/riposte' },
      { name: 'shield bash', level: 21, url: '/help/shield-bash' },
      { name: 'overhead', level: 22, url: '/help/overhead' },
      { name: 'backhand', level: 22, url: '/help/backhand' },
      { name: 'charge set', level: 23, url: '/help/charge-set' },
      { name: 'divine health', level: 24, url: '/help/divine-health' },
      { name: 'cross slice', level: 25, url: '/help/cross-slice-crossslice' },
      { name: 'warrior spirit', level: 26, url: '/help/warrior-spirit' },
      { name: 'impale', level: 27, url: '/help/impale' },
      { name: 'aura of courage', level: 29, url: '/help/aura-of-courage' },
      { name: 'spiritual healing', level: 33, url: '/help/spiritual-healing' },
    ],
    basicSpells: [
      { name: 'armor', level: 2, url: '/help/armor' },
      { name: 'cure light', level: 2, url: '/help/cure-light' },
      { name: 'bless', level: 4, url: '/help/bless' },
      { name: 'create food', level: 4, url: '/help/create-food' },
      { name: 'refresh', level: 4, url: '/help/refresh' },
      { name: 'cure serious', level: 5, url: '/help/cure-serious' },
      { name: 'detect evil', level: 5, url: '/help/detect-evil' },
      { name: 'protection', level: 5, url: '/help/protection' },
      { name: 'create water', level: 6, url: '/help/create-water' },
      { name: 'dispel evil', level: 7, url: '/help/dispel-evil' },
      { name: 'detect invis', level: 8, url: '/help/detect-invis' },
      { name: 'cure critical', level: 9, url: '/help/cure-critical' },
      { name: 'create spring', level: 11, url: '/help/create-spring' },
      { name: 'flamestrike', level: 12, url: '/help/flamestrike' },
      { name: 'wrath', level: 16, url: '/help/wrath-vengeance' },
      { name: 'calm', level: 17, url: '/help/calm' },
      { name: 'frenzy', level: 18, url: '/help/frenzy' },
      { name: 'summon', level: 18, url: '/help/summon' },
      { name: 'banishment', level: 19, url: '/help/banishment' },
      { name: 'lightshield', level: 20, url: '/help/lightshield' },
      { name: 'turn undead', level: 21, url: '/help/turn-undead' },
      { name: 'word of recall', level: 22, url: '/help/word-of-recall' },
      { name: 'protectorate', level: 23, url: '/help/protectorate' },
      { name: 'holy prayer', level: 24, url: '/help/holy-prayer' },
      { name: 'shield of faith', level: 28, url: '/help/shield-of-faith' },
      { name: 'sanctify object', level: 30, url: '/help/sanctify-object' },
      { name: 'templars sight', level: 32, url: '/help/templars-sight' },
    ],
  },

  [Class.RANGER]: {
    name: Class.RANGER,
    title: 'Ranger',
    slug: 'ranger',
    description: 'Forest warriors, learned in woodlore and survival.',
    features: [],
    xpPenalty: 10,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL],
    reference: [
      { label: 'specialization', url: '/help/specialization-specialize' },
    ],
    weapons: [
      { name: 'axe', level: 1 },
      { name: 'dagger', level: 1 },
      { name: 'flail', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
      { name: 'bow', level: 1 },
      { name: 'crossbow', level: 1 },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'bash', level: 2, url: '/help/bash' },
      { name: 'dirt kicking', level: 2, url: '/help/dirt-dirt-kicking' },
      { name: 'quiet movement', level: 3, url: '/help/quiet-movement' },
      { name: 'parry', level: 3, url: '/help/parry' },
      { name: 'butcher', level: 4, url: '/help/butcher' },
      { name: 'acute vision', level: 5, url: '/help/camouflage-acute-vision' },
      { name: 'pathfinding', level: 5 },
      { name: 'hand to hand', level: 6, url: '/help/hand-to-hand' },
      { name: 'second attack', level: 7, url: '/help/second-attack' },
      { name: 'riding', level: 7, url: '/help/mount-ride-dismount-riding' },
      { name: 'camouflage', level: 8, url: '/help/camouflage-acute-vision' },
      { name: 'herb', level: 8, url: '/help/herbs-curative-herbs' },
      { name: 'enhanced damage', level: 9, url: '/help/enhanced-damage' },
      { name: 'meditation', level: 9, url: '/help/meditation' },
      { name: 'find water', level: 10, url: '/help/find-water' },
      { name: 'ambush', level: 10, url: '/help/ambush' },
      { name: 'fast healing', level: 11, url: '/help/fast-healing' },
      { name: 'skin', level: 11 },
      { name: 'dodge', level: 12, url: '/help/dodge' },
      { name: 'snare', level: 12, url: '/help/snare' },
      { name: 'mounted fighting', level: 12, url: '/help/mounted-fighting' },
      { name: 'lore', level: 13, url: '/help/lore' },
      { name: 'dual wield', level: 13, url: '/help/dual-dual-wield' },
      { name: 'ranger ammo', level: 13, url: '/help/ranger-ammo-rangerammo' },
      {
        name: 'protection heat cold',
        level: 14,
        url: '/help/protection-heat-cold',
      },
      { name: 'camp', level: 14, url: '/help/camp' },
      { name: 'stance', level: 14, url: '/help/stance-stances-relax' },
      { name: 'shield block', level: 15, url: '/help/shield-block' },
      { name: 'curative herbs', level: 15, url: '/help/herbs-curative-herbs' },
      {
        name: 'third attack',
        level: 16,
        url: '/help/third-attack-fourth-attack',
      },
      { name: 'barkskin', level: 17, url: '/help/barkskin' },
      { name: 'flank', level: 17, url: '/help/flanking' },
      { name: 'animal call', level: 18, url: '/help/animal-call' },
      { name: 'ranger staff', level: 19, url: '/help/ranger-staff' },
      { name: 'moving ambush', level: 20, url: '/help/moving-ambush' },
      {
        name: 'wilderness familiarity',
        level: 21,
        url: '/help/wilderness-familiarity',
      },
      {
        name: 'tailored skins',
        level: 22,
        url: '/help/tailored-skins-tailor-skins',
      },
      { name: 'creep', level: 23, url: '/help/creep' },
      { name: 'hunt', level: 25, url: '/help/hunt' },
      {
        name: 'forest guardianship',
        level: 26,
        url: '/help/forest-guardianship-guardianship',
      },
      { name: 'warrior spirit', level: 26, url: '/help/warrior-spirit' },
    ],
    specChoices: 2,
    specAllowed: [
      Specs.WHIP_FLAIL,
      Specs.STAFF,
      Specs.RANGED,
      Specs.AXE,
      Specs.HAND_TO_HAND,
      Specs.SPEAR,
    ],
    specSkills: [
      {
        id: Specs.STAFF,
        skills: [
          { name: 'overhead', level: 20, url: '/help/overhead' },
          { name: 'pugil', level: 10, url: '/help/pugil' },
          { name: 'leg sweep', level: 16, url: '/help/leg-sweep-legsweep' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
        ],
      },
      {
        id: Specs.RANGED,
        skills: [
          { name: 'accuracy', level: 11, url: '/help/accuracy' },
          { name: 'quick shot', level: 15, url: '/help/quick-shot-quickshot' },
          { name: 'aimed shot', level: 19, url: '/help/aimed-shot' },
          { name: 'volley', level: 26, url: '/help/volley' },
        ],
      },
      {
        id: Specs.AXE,
        skills: [
          { name: 'pincer', level: 21, url: '/help/pincer' },
          { name: 'cleave', level: 26, url: '/help/cleave' },
          { name: 'chop', level: 14, url: '/help/chop' },
          {
            name: 'concussion strike',
            level: 23,
            url: '/help/concussion-strike-concussion',
          },
          { name: 'wrist chop', level: 26, url: '/help/wrist-chop-wristchop' },
          { name: 'meatgrinder', level: 28, url: '/help/meatgrinder' },
        ],
      },
      {
        id: Specs.SPEAR,
        skills: [
          { name: 'charge set', level: 22, url: '/help/charge-set' },
          { name: 'impale', level: 26, url: '/help/impale' },
          { name: 'jab', level: 16, url: '/help/jab' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
          { name: 'harpoon', level: 31, url: '/help/harpoon' },
        ],
      },
      {
        id: Specs.WHIP_FLAIL,
        skills: [
          { name: 'flog', level: 16, url: '/help/flog-flogging' },
          { name: 'strip weapon', level: 16, url: '/help/strip-weapon' },
          { name: 'choke', level: 21, url: '/help/choke' },
          { name: 'lash', level: 11, url: '/help/lash' },
          { name: 'pull', level: 19, url: '/help/pull' },
          { name: 'eyejab', level: 13, url: '/help/eyejab' },
        ],
      },
      {
        id: Specs.HAND_TO_HAND,
        skills: [
          {
            name: 'iron strike',
            level: 11,
            url: '/help/iron-strike-ironstrike',
          },
          { name: 'throw', level: 16, url: '/help/throw' },
          { name: 'leaping strike', level: 20, url: '/help/leaping-strike' },
          { name: 'ground control', level: 18, url: '/help/ground-control' },
          { name: 'hand block', level: 12, url: '/help/hand-block' },
          { name: 'grapple', level: 10, url: '/help/grapple-grappling' },
        ],
      },
    ],
  },
  [Class.CLERIC]: {
    name: Class.CLERIC,
    title: 'Cleric',
    slug: 'cleric',
    description: 'Followers of the Gods.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [{ label: 'worship', url: '/help/worship' }],
    weapons: [
      { name: 'flail', level: 1 },
      { name: 'mace', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
    ],
    consumables: [
      { name: 'staves', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'wands', level: 1, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'meditation', level: 4, url: '/help/meditation' },
      { name: 'fast healing', level: 8, url: '/help/fast-healing' },
      { name: 'hand to hand', level: 10, url: '/help/hand-to-hand' },
      { name: 'riding', level: 10, url: '/help/mount-ride-dismount-riding' },
      { name: 'trance', level: 11, url: '/help/trance' },
      { name: 'kick', level: 12, url: '/help/kick' },
      { name: 'haggle', level: 13, url: '/help/haggle' },
      { name: 'shield block', level: 14, url: '/help/shield-block' },
      { name: 'mace swing', level: 15, url: '/help/mace-swing' },
      { name: 'parry', level: 16, url: '/help/parry' },
      { name: 'mounted fighting', level: 18, url: '/help/mounted-fighting' },
      { name: 'second attack', level: 20, url: '/help/second-attack' },
    ],
    basicSpells: [
      { name: 'armor', level: 1, url: '/help/armor' },
      { name: 'cure light', level: 1, url: '/help/cure-light' },
      { name: 'create food', level: 2, url: '/help/create-food' },
      { name: 'faerie fire', level: 2, url: '/help/faerie-fire' },
      { name: 'continual light', level: 3, url: '/help/continual-light' },
      { name: 'cure serious', level: 3, url: '/help/cure-serious' },
      { name: 'create water', level: 4, url: '/help/create-water' },
      { name: 'detect evil', level: 4, url: '/help/detect-evil' },
      { name: 'detect good', level: 4, url: '/help/detect-good' },
      { name: 'bless', level: 5, url: '/help/bless' },
      { name: 'refresh', level: 5, url: '/help/refresh' },
      { name: 'cure blindness', level: 6, url: '/help/cure-blindness' },
      { name: 'detect invis', level: 6, url: '/help/detect-invis' },
      { name: 'protection', level: 6, url: '/help/protection' },
      { name: 'giant strength', level: 7, url: '/help/giant-strength' },
      { name: 'know alignment', level: 7, url: '/help/know-alignment' },
      { name: 'cure critical', level: 8, url: '/help/cure-critical' },
      { name: 'cure disease', level: 9, url: '/help/cure-disease' },
      { name: 'cure poison', level: 9, url: '/help/cure-poison' },
      { name: 'infravision', level: 9, url: '/help/infravision' },
      { name: 'remove curse', level: 10, url: '/help/remove-curse' },
      { name: 'ring of sanctity', level: 11, url: '/help/ring-of-sanctity' },
      { name: 'curse', level: 12, url: '/help/curse' },
      { name: 'calm', level: 13, url: '/help/calm' },
      { name: 'locate object', level: 13, url: '/help/locate-object' },
      { name: 'create spring', level: 14, url: '/help/create-spring' },
      { name: 'fly', level: 14, url: '/help/fly' },
      { name: 'identify', level: 14, url: '/help/identify' },
      { name: 'faerie fog', level: 15, url: '/help/faerie-fog' },
      { name: 'teleport', level: 16, url: '/help/teleport-group-teleport' },
      { name: 'awaken', level: 17, url: '/help/awaken' },
      { name: 'frenzy', level: 18, url: '/help/frenzy' },
      { name: 'restoration', level: 18, url: '/help/restoration' },
      {
        name: 'cancellation',
        level: 19,
        url: '/help/cancellation-dispel-magic',
      },
      { name: 'word of recall', level: 19, url: '/help/word-of-recall' },
      { name: 'pass door', level: 20, url: '/help/pass-door' },
      { name: 'turn undead', level: 21, url: '/help/turn-undead' },
      { name: 'consecrate', level: 26, url: '/help/consecrate' },
    ],
    specSkills: [
      {
        id: Specs.GOD_KIRI_JOLITH,
        skills: [
          { name: 'enhanced damage', level: 15, url: '/help/enhanced-damage' },
        ],
      },
      {
        id: Specs.GOD_PALADINE,
        skills: [
          { name: 'enhanced damage', level: 15, url: '/help/enhanced-damage' },
        ],
      },
      {
        id: Specs.GOD_MISHAKAL,
        skills: [
          { name: 'healing mastery', level: 32, url: '/help/healing-mastery' },
        ],
      },
      {
        id: Specs.GOD_MAJERE,
        skills: [
          { name: 'flowing block', level: 14, url: '/help/flowing-block' },
          { name: 'swipe', level: 16, url: '/help/swipe' },
          { name: 'strike', level: 18, url: '/help/strike' },
          { name: 'brace', level: 28, url: '/help/brace' },
        ],
      },
      {
        id: Specs.GOD_REORX,
        skills: [
          { name: 'enhanced damage', level: 15, url: '/help/enhanced-damage' },
        ],
      },
      {
        id: Specs.GOD_CHISLEV,
        skills: [], // Chislev has no additional skills beyond basic skills
      },
      {
        id: Specs.GOD_SIRRION,
        skills: [], // Sirrion has no additional skills beyond basic skills
      },
    ],
    specSpells: [
      {
        id: Specs.GOD_KIRI_JOLITH,
        spells: [
          { name: 'summon', level: 15, url: '/help/summon' },
          { name: 'hammerfist', level: 19, url: '/help/hammerfist' },
          { name: 'blessed reversal', level: 26, url: '/help/blessed-reversal' },
          { name: 'foresight', level: 27, url: '/help/foresight' },
          { name: 'call deva', level: 30, url: '/help/call-deva' },
        ],
      },
      {
        id: Specs.GOD_PALADINE,
        spells: [
          { name: 'summon', level: 15, url: '/help/summon' },
          { name: 'hammerfist', level: 19, url: '/help/hammerfist' },
          { name: 'repel evil', level: 22, url: '/help/repel-evil' },
          { name: 'lifeline', level: 26, url: '/help/lifeline' },
          { name: 'foresight', level: 27, url: '/help/foresight' },
          { name: 'call deva', level: 30, url: '/help/call-deva' },
        ],
      },
      {
        id: Specs.GOD_MISHAKAL,
        spells: [
          { name: 'gate', level: 11, url: '/help/gate' },
          { name: 'resist lightning', level: 12, url: '/help/resist-lightning' },
          { name: 'stoneskin', level: 17, url: '/help/ironskin-stoneskin' },
          { name: 'crown of archons', level: 18, url: '/help/crown-of-archons' },
          { name: 'resist paralysis', level: 18, url: '/help/resist-paralysis' },
          { name: 'redemption', level: 20, url: '/help/redemption' },
          { name: 'resist undead', level: 21, url: '/help/resist-undead' },
          { name: 'imbue regeneration', level: 22, url: '/help/imbue-regeneration' },
          { name: 'repel evil', level: 22, url: '/help/repel-evil' },
          { name: 'group teleport', level: 23, url: '/help/teleport-group-teleport' },
          { name: 'heal', level: 24, url: '/help/heal' },
          { name: 'healing sleep', level: 24, url: '/help/healing-sleep' },
          { name: 'mass healing', level: 25, url: '/help/mass-healing' },
          { name: 'safety', level: 26, url: '/help/safety' },
          { name: 'utter heal', level: 30, url: '/help/utter-heal' },
          { name: 'rejuvenation chamber', level: 31, url: '/help/rejuvenation-chamber' },
        ],
      },
      {
        id: Specs.GOD_MAJERE,
        spells: [
          { name: 'gate', level: 11, url: '/help/gate' },
          { name: 'resist lightning', level: 12, url: '/help/resist-lightning' },
          { name: 'stoneskin', level: 17, url: '/help/ironskin-stoneskin' },
          { name: 'imbue regeneration', level: 22, url: '/help/imbue-regeneration' },
          { name: 'group teleport', level: 23, url: '/help/teleport-group-teleport' },
          { name: 'heal', level: 24, url: '/help/heal' },
          { name: 'healing sleep', level: 24, url: '/help/healing-sleep' },
          { name: 'mass healing', level: 25, url: '/help/mass-healing' },
          { name: 'divine presence', level: 25, url: '/help/divine-presence' },
          { name: 'safety', level: 26, url: '/help/safety' },
        ],
      },
      {
        id: Specs.GOD_REORX,
        spells: [
          { name: 'sparks of the forge', level: 8, url: '/help/sparks-of-the-forge' },
          { name: 'resist fire', level: 9, url: '/help/resist-fire' },
          { name: 'resist cold', level: 10, url: '/help/resist-cold' },
          { name: 'gate', level: 11, url: '/help/gate' },
          { name: 'resist lightning', level: 12, url: '/help/resist-lightning' },
          { name: 'cure mortal wounds', level: 15, url: '/help/cure-mortal-wounds' },
          { name: 'shelter of the earth', level: 17, url: '/help/shelter-of-the-earth' },
          { name: 'molten iron', level: 19, url: '/help/molten-iron' },
          { name: 'roots of rock', level: 20, url: '/help/roots-of-rock' },
          { name: 'blade barrier', level: 21, url: '/help/blade-barrier' },
          { name: 'forged hammer', level: 21, url: '/help/forged-hammer' },
          { name: 'group teleport', level: 23, url: '/help/teleport-group-teleport' },
          { name: 'flesh to dust', level: 24, url: '/help/flesh-to-dust' },
        ],
      },
      {
        id: Specs.GOD_CHISLEV,
        spells: [
          { name: 'blindness', level: 4, url: '/help/blindness' },
          { name: 'resist lightning', level: 12, url: '/help/resist-lightning' },
          { name: 'briar shield', level: 13, url: '/help/briar-shield' },
          { name: 'mana shield', level: 14, url: '/help/mana-shield-manashield' },
          { name: 'aid', level: 14, url: '/help/aid' },
          { name: 'summon plant seed', level: 15, url: '/help/summon-plant-seed' },
          { name: 'cure mortal wounds', level: 15, url: '/help/cure-mortal-wounds' },
          { name: 'thunderbolt', level: 16, url: '/help/thunderbolt' },
          { name: 'forest growth', level: 16, url: '/help/forest-growth' },
          { name: 'venomous cloud', level: 17, url: '/help/venomous-cloud' },
          { name: 'dispel magic', level: 17, url: '/help/cancellation-dispel-magic' },
          { name: 'summon water elemental', level: 18, url: '/help/summon-water-elemental' },
          { name: 'resist negative', level: 19, url: '/help/resist-negative' },
          { name: 'trueform', level: 20, url: '/help/trueform' },
          { name: 'forest haven', level: 21, url: '/help/forest-haven' },
          { name: 'wildhome', level: 22, url: '/help/wildhome' },
          { name: 'wall of roots', level: 22, url: '/help/wall-of-roots' },
          { name: 'hurricane', level: 24, url: '/help/hurricane' },
          { name: 'weapon resistance', level: 26, url: '/help/weapon-resistance' },
          { name: 'rock to mud', level: 27, url: '/help/rock-to-mud' },
          { name: 'grass to razors', level: 27, url: '/help/grass-to-razors' },
          { name: 'summon air elemental', level: 28, url: '/help/summon-air-elemental' },
          { name: 'incarnation of nature', level: 30, url: '/help/incarnation-of-nature' },
          { name: 'summon thorn elemental', level: 32, url: '/help/summon-thorn-elemental' },
        ],
      },
      {
        id: Specs.GOD_SIRRION,
        spells: [
          { name: 'resist cold', level: 10, url: '/help/resist-cold' },
          { name: 'gate', level: 11, url: '/help/gate' },
          { name: 'resist lightning', level: 12, url: '/help/resist-lightning' },
          { name: 'aid', level: 14, url: '/help/aid' },
          { name: 'cure mortal wounds', level: 15, url: '/help/cure-mortal-wounds' },
          { name: 'blaze', level: 16, url: '/help/blaze' },
          { name: 'flame aura', level: 20, url: '/help/flame-aura' },
          { name: 'group teleport', level: 23, url: '/help/teleport-group-teleport' },
          { name: 'flame ring', level: 26, url: '/help/flame-ring' },
          { name: 'morph liquid', level: 30, url: '/help/morph-liquid' },
        ],
      },
    ],
    worshipChoices: [
      {
        spec: Specs.GOD_KIRI_JOLITH,
        desc: ['a sign of the silver War-hammer'], // TODO: Add descriptions for Kiri-Jolith
        allowedAlignments: [Alignment.GOOD],
      },
      {
        spec: Specs.GOD_PALADINE,
        desc: ['a sign of the Platinum dragon claw'], // TODO: Add descriptions for Paladine
        allowedAlignments: [Alignment.GOOD],
      },
      {
        spec: Specs.GOD_MISHAKAL,
        desc: ['a sign of the Healer'], // TODO: Add descriptions for Mishakal
        allowedAlignments: [Alignment.GOOD],
      },
      {
        spec: Specs.GOD_MAJERE,
        desc: ['a sign of the clenched Fist'], // TODO: Add descriptions for Majere
        allowedAlignments: [Alignment.GOOD],
        excludedBasicSkills: ['shield block', 'mace swing'],
      },
      {
        spec: Specs.GOD_REORX,
        desc: ['a sign of the forging Hammer'],
        allowedAlignments: [Alignment.NEUTRAL],
      },
      {
        spec: Specs.GOD_CHISLEV,
        desc: ['a sign of Oak and Earth'],
        allowedAlignments: [Alignment.NEUTRAL],
      },
      {
        spec: Specs.GOD_SIRRION,
        desc: ['a sign of twin sparks'],
        allowedAlignments: [Alignment.NEUTRAL],
      },
      {
        spec: Specs.GOD_MORGION,
        desc: ['a sign of the decaying Goats head'],
        allowedAlignments: [Alignment.EVIL],
      },
      {
        spec: Specs.GOD_CHEMOSH,
        desc: ['a sign of the Inverted cross'],
        allowedAlignments: [Alignment.EVIL],
      },
      {
        spec: Specs.GOD_SARGONNAS,
        desc: ['a sign of raging fire'],
        allowedAlignments: [Alignment.EVIL],
      },
      {
        spec: Specs.GOD_TAKHISIS,
        desc: ['a sign of Five clenched dragon claws'],
        allowedAlignments: [Alignment.EVIL],
      },
      {
        spec: Specs.GOD_HIDDUKEL,
        desc: ['a sign of a single gold coin'],
        allowedAlignments: [Alignment.EVIL],
      },
    ],
  },

  [Class.DRUID]: {
    name: Class.DRUID,
    title: 'Druid',
    slug: 'druid',
    description: 'Disciples of natural magic and control.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL],
    reference: [{ label: 'kinship', url: '/help/animal-kinship-kinship' }],
    weapons: [
      { name: 'axe', level: 1 },
      { name: 'mace', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'staff', level: 1 },
    ],
    consumables: [
      { name: 'staves', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'wands', level: 1, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'quiet movement', level: 2, url: '/help/quiet-movement' },
      { name: 'dirt kicking', level: 3, url: '/help/dirt-dirt-kicking' },
      { name: 'meditation', level: 4, url: '/help/meditation' },
      { name: 'pathfinding', level: 5 },
      {
        name: 'protection heat cold',
        level: 6,
        url: '/help/protection-heat-cold',
      },
      { name: 'curative herbs', level: 7, url: '/help/herbs-curative-herbs' },
      { name: 'trance', level: 8, url: '/help/trance' },
      { name: 'riding', level: 9, url: '/help/mount-ride-dismount-riding' },
      { name: 'forage', level: 10, url: '/help/forage' },
      { name: 'hand to hand', level: 11, url: '/help/hand-to-hand' },
      { name: 'pugil', level: 12, url: '/help/pugil' },
      { name: 'nature solace', level: 12, url: '/help/nature-solace' },
      { name: 'shield block', level: 13, url: '/help/shield-block' },
      { name: 'second attack', level: 14, url: '/help/second-attack' },
      { name: 'parry', level: 15, url: '/help/parry' },
      { name: 'gather herbs', level: 15, url: '/help/gather-herbs' },
      { name: 'barkskin', level: 16, url: '/help/barkskin' },
      { name: 'fast healing', level: 16, url: '/help/fast-healing' },
      { name: 'haggle', level: 16, url: '/help/haggle' },
      { name: 'mounted fighting', level: 16, url: '/help/mounted-fighting' },
      { name: 'sustenance', level: 17, url: '/help/sustenance' },
      {
        name: 'enhanced damage with staff',
        level: 19,
        url: '/help/enhanced-damage-with-staff-third',
      },
      {
        name: 'attune with forest',
        level: 20,
        url: '/help/attune-with-forest',
      },
      {
        name: 'third attack with staff',
        level: 23,
        url: '/help/enhanced-damage-with-staff-third',
      },
      { name: 'stand off', level: 26, url: '/help/stand-off' },
    ],
    basicSpells: [
      {
        name: 'cure light',
        level: 1,
        url: '/help/cure-light-cure-serious-cure',
      },
      { name: 'carapace', level: 1, url: '/help/thornskin-carapace' },
      { name: 'refresh', level: 2, url: '/help/refresh' },
      {
        name: 'create water',
        level: 3,
        url: '/help/create-water-create-spring',
      },
      { name: 'sticks to snakes', level: 4, url: '/help/sticks-to-snakes' },
      { name: 'bless', level: 5, url: '/help/bless' },
      {
        name: 'cure serious',
        level: 5,
        url: '/help/cure-light-cure-serious-cure',
      },
      {
        name: 'create spring',
        level: 6,
        url: '/help/create-water-create-spring',
      },
      { name: 'cure poison', level: 6, url: '/help/cure-poison-cure-disease' },
      { name: 'leaf blades', level: 7, url: '/help/leaf-blades-leafblades' },
      {
        name: 'cure critical',
        level: 8,
        url: '/help/cure-light-cure-serious-cure',
      },
      { name: 'resist lightning', level: 8 },
      { name: 'cure disease', level: 9, url: '/help/cure-poison-cure-disease' },
      { name: 'identify', level: 10, url: '/help/identify' },
      {
        name: 'starburst',
        level: 10,
        url: '/help/razorwind-starburst-sunburst-sunray',
      },
      { name: 'cure blindness', level: 11, url: '/help/cure-blindness' },
      { name: 'fly', level: 12, url: '/help/fly' },
      {
        name: 'sunburst',
        level: 13,
        url: '/help/razorwind-starburst-sunburst-sunray',
      },
      { name: 'forest haven', level: 13, url: '/help/forest-haven' },
      { name: 'frenzy', level: 14, url: '/help/frenzy' },
      { name: 'locate object', level: 14, url: '/help/locate-object' },
      { name: 'entanglement', level: 14, url: '/help/entanglement' },
      { name: 'faerie fog', level: 15, url: '/help/faerie-fog' },
      {
        name: 'razorwind',
        level: 16,
        url: '/help/razorwind-starburst-sunburst-sunray',
      },
      { name: 'nature blessing', level: 17, url: '/help/nature-blessing' },
      { name: 'geyser', level: 18, url: '/help/geyser' },
      { name: 'thornskin', level: 19, url: '/help/thornskin-carapace' },
      {
        name: 'cancellation',
        level: 20,
        url: '/help/cancellation-dispel-magic',
      },
      { name: 'moonwell', level: 20, url: '/help/moonwell-moonstone' },
      { name: 'treeform', level: 21, url: '/help/treeform' },
      { name: 'living grass', level: 21, url: '/help/living-grass' },
      { name: 'wildhome', level: 22, url: '/help/wildhome' },
      { name: 'shilleigh', level: 22, url: '/help/shilleigh' },
      { name: 'call treant', level: 24, url: '/help/call-treant' },
      {
        name: 'sunray',
        level: 25,
        url: '/help/razorwind-starburst-sunburst-sunray',
      },
      { name: 'forest growth', level: 26, url: '/help/forest-growth' },
      { name: 'trueform', level: 27, url: '/help/trueform' },
      {
        name: 'imbue treant with spell',
        level: 28,
        url: '/help/imbue-treant-with-spell',
      },
    ],
    specSpells: [
      {
        id: Specs.KINSHIP_ALL,
        spells: [
          { name: 'first random animal form', level: 15 },
          { name: 'second random animal form', level: 19 },
          { name: 'owlform', level: 23, url: '/help/owlform-owl-form' },
          {
            name: 'bearform',
            level: 27,
            url: '/help/wolfform-boarform-bearform',
          },
        ],
      },
      {
        id: Specs.KINSHIP_WOLF,
        spells: [
          {
            name: 'greater wolf form',
            level: 18,
            url: '/help/druid-forms-greater-boar-greater',
          },
        ],
      },
      {
        id: Specs.KINSHIP_BOAR,
        spells: [
          {
            name: 'greater boar form',
            level: 18,
            url: '/help/druid-forms-greater-boar-greater',
          },
        ],
      },
      {
        id: Specs.KINSHIP_ORANGUTAN,
        spells: [
          {
            name: 'orangoutang form',
            level: 19,
            url: '/help/druid-forms-greater-boar-greater',
          },
        ],
      },
    ],
    kinshipChoices: [
      {
        spec: Specs.KINSHIP_ALL,
        desc: [
          'Obtains two random minor animal forms.',
          'Has an owlform. Which is able to fly across the lands.',
          'Has a bearform.',
        ],
      },
      {
        spec: Specs.KINSHIP_WOLF,
        desc: [
          'Is able to cast spells upon itself while in animal form.',
          'Is able to maintain itself as a greater wolf without using mana.',
        ], // TODO: Add descriptions for Greater Wolf kinship
      },
      {
        spec: Specs.KINSHIP_BOAR,
        desc: [
          'Is able to cast spells upon itself while in animal form.',
          'Is able to maintain itself as a greater boar without using mana.',
        ],
      },
      {
        spec: Specs.KINSHIP_ORANGUTAN,
        desc: [
          'Is able to cast spells upon itself while in animal form.',
          'Is able to maintain itself as an orangoutang without using mana.',
        ],
      },
    ],
  },

  [Class.THIEF]: {
    name: Class.THIEF,
    title: 'Thief',
    slug: 'thief',
    description: "The skilled stealer of other people's belongings.",
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [{ label: 'memorizing spell', url: '/help/memorizing-spell' }],
    weapons: [
      { name: 'dagger', level: 1 },
      { name: 'mace', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'staff', level: 1 },
    ],
    consumables: [
      { name: 'scrolls', level: 1, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'backstab', level: 1, url: '/help/backstab' },
      { name: 'dodge', level: 1, url: '/help/dodge' },
      { name: 'trip', level: 1, url: '/help/trip' },
      { name: 'haggle', level: 1, url: '/help/haggle' },
      { name: 'peek', level: 1, url: '/help/peek' },
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'dirt kicking', level: 2, url: '/help/dirt-dirt-kicking' },
      { name: 'hide', level: 2, url: '/help/hide' },
      { name: 'sneak', level: 3, url: '/help/sneak' },
      { name: 'steal', level: 4, url: '/help/steal' },
      { name: 'pick lock', level: 5, url: '/help/pick-lock' },
      { name: 'lore', level: 6, url: '/help/lore' },
      { name: 'shield block', level: 7, url: '/help/shield-block' },
      { name: 'detect hidden', level: 8, url: '/help/detect-hidden' },
      { name: 'circle stab', level: 8, url: '/help/circle-stab' },
      { name: 'downstrike', level: 9, url: '/help/downstrike' },
      { name: 'memorizing spell', level: 10, url: '/help/memorizing-spell' },
      { name: 'disarm', level: 10, url: '/help/disarm' },
      { name: 'second attack', level: 10, url: '/help/second-attack' },
      { name: 'riding', level: 10, url: '/help/mount-ride-dismount-riding' },
      { name: 'kick', level: 11, url: '/help/kick' },
      { name: 'parry', level: 11, url: '/help/parry' },
      { name: 'hand to hand', level: 12, url: '/help/hand-to-hand' },
      { name: 'meditation', level: 12, url: '/help/meditation' },
      {
        name: 'attack of opportunity',
        level: 12,
        url: '/help/attack-of-opportunity',
      },
      { name: 'fast healing', level: 13, url: '/help/fast-healing' },
      { name: 'escape', level: 13, url: '/help/escape' },
      {
        name: 'set spiked trap',
        level: 14,
        url: '/help/set-spiked-trap-set-poison-trap-set-flaming-trap-trap-trap-disarm',
      },
      { name: 'recovery', level: 14, url: '/help/recovery' },
      { name: 'bleed', level: 14, url: '/help/bleed' },
      { name: 'blackjack', level: 15, url: '/help/blackjack' },
      { name: 'sense spell', level: 15, url: '/help/sense-spell' },
      {
        name: 'trap disarm',
        level: 16,
        url: '/help/set-spiked-trap-set-poison-trap-set-flaming-trap-trap-trap-disarm',
      },
      { name: 'dual wield', level: 16, url: '/help/dual-dual-wield' },
      { name: 'knife', level: 16, url: '/help/knife' },
      { name: 'rogues awareness', level: 16, url: '/help/rogues-awareness' },
      { name: 'enhanced damage', level: 17, url: '/help/enhanced-damage' },
      { name: 'mounted fighting', level: 17, url: '/help/mounted-fighting' },
      {
        name: 'third attack',
        level: 18,
        url: '/help/third-attack-fourth-attack',
      },
      { name: 'envenom', level: 19, url: '/help/envenom' },
      { name: 'tackle', level: 20, url: '/help/tackle' },
      { name: 'relock', level: 21, url: '/help/relock' },
      {
        name: 'set poison trap',
        level: 22,
        url: '/help/set-spiked-trap-set-poison-trap-set-flaming-trap-trap-trap-disarm',
      },
      { name: 'item forgery', level: 22, url: '/help/item-forgery' },
      { name: 'undercut', level: 23, url: '/help/undercut' },
      { name: 'loot', level: 24, url: '/help/loot' },
      { name: 'dual backstab', level: 25, url: '/help/dual-backstab' },
      { name: 'superb reflexes', level: 25, url: '/help/superb-reflexes' },
      { name: 'pilfer', level: 26, url: '/help/pilfer' },
      { name: 'restrike', level: 27, url: '/help/restrike' },
      { name: 'hamstring attack', level: 30, url: '/help/hamstring-attack' },
    ],
  },

  [Class.ASSASSIN]: {
    name: Class.ASSASSIN,
    title: 'Assassin',
    slug: 'assassin',
    description: 'Specialists in stealth and unarmed killing.',
    features: [],
    xpPenalty: 15,
    allowedAlignments: [Alignment.GOOD, Alignment.EVIL],
    reference: [{ label: 'wayfollow', url: '/help/wayfollow-waypath' }],
    weapons: [
      { name: 'dagger', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'staff', level: 1 },
    ],
    consumables: [
      { name: 'staves', level: 1, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'dodge', level: 1, url: '/help/dodge' },
      { name: 'hand to hand', level: 1, url: '/help/hand-to-hand' },
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'dirt kicking', level: 2, url: '/help/dirt-dirt-kicking' },
      { name: 'trip', level: 3, url: '/help/trip' },
      { name: 'enhanced damage', level: 4, url: '/help/enhanced-damage' },
      { name: 'kick', level: 4, url: '/help/kick' },
      { name: 'meditation', level: 5, url: '/help/meditation' },
      { name: 'sneak', level: 5, url: '/help/sneak' },
      { name: 'haggle', level: 6, url: '/help/haggle' },
      { name: 'hide', level: 6, url: '/help/hide' },
      { name: 'hand block', level: 7, url: '/help/hand-block' },
      { name: 'detect hidden', level: 8, url: '/help/detect-hidden' },
      { name: 'second attack', level: 8, url: '/help/second-attack' },
      { name: 'parry', level: 9, url: '/help/parry' },
      { name: 'fast healing', level: 9, url: '/help/fast-healing' },
      { name: 'riding', level: 9, url: '/help/mount-ride-dismount-riding' },
      { name: 'caltraps', level: 10, url: '/help/caltraps' },
      { name: 'endure', level: 10, url: '/help/endure' },
      { name: 'disarm', level: 10, url: '/help/disarm' },
      { name: 'nerve', level: 11, url: '/help/nerve' },
      { name: 'follow through', level: 11, url: '/help/follow-through' },
      { name: 'bash', level: 11, url: '/help/bash' },
      { name: 'dual wield', level: 12, url: '/help/dual-dual-wield' },
      { name: 'pick lock', level: 12, url: '/help/pick-lock' },
      {
        name: 'attack of opportunity',
        level: 12,
        url: '/help/attack-of-opportunity',
      },
      { name: 'lore', level: 13, url: '/help/lore' },
      { name: 'throw', level: 13, url: '/help/throw' },
      { name: 'vanish', level: 13, url: '/help/vanish' },
      { name: 'poison dust', level: 14, url: '/help/poison-dust' },
      { name: 'style tiger', level: 14, url: '/help/styles' },
      { name: 'recovery', level: 14, url: '/help/recovery' },
      { name: 'shield block', level: 15, url: '/help/shield-block' },
      { name: 'iron strike', level: 15, url: '/help/iron-strike-ironstrike' },
      { name: 'mounted fighting', level: 15, url: '/help/mounted-fighting' },
      { name: 'shuriken', level: 16, url: '/help/shuriken' },
      { name: 'blindness dust', level: 16, url: '/help/blindness-dust' },
      {
        name: 'third attack',
        level: 16,
        url: '/help/third-attack-fourth-attack',
      },
      { name: 'strangle', level: 17, url: '/help/strangle' },
      { name: 'leaping strike', level: 18, url: '/help/leaping-strike' },
      { name: 'ground control', level: 19, url: '/help/ground-control' },
      {
        name: 'find vulnerability',
        level: 21,
        url: '/help/find-vulnerability',
      },
      { name: 'assassinate', level: 26, url: '/help/assassinate' },
    ],
    basicSpells: [
      { name: 'invisibility', level: 7, url: '/help/invisibility' },
      { name: 'infravision', level: 9, url: '/help/infravision' },
      { name: 'detect invis', level: 10, url: '/help/detect-invisibility' },
      { name: 'locate object', level: 17, url: '/help/locate-object' },
    ],
    specSpells: [
      {
        id: Specs.WAY_SHADOWS,
        spells: [
          { name: 'word of recall', level: 21, url: '/help/word-of-recall' },
        ],
      },
    ],
    specSkills: [
      {
        id: Specs.WAY_SHADOWS,
        skills: [
          { name: 'style python', level: 15, url: '/help/styles' },
          { name: 'style viper', level: 15, url: '/help/styles' },
          { name: 'kidnap', level: 16, url: '/help/kidnap' },
          { name: 'stalk', level: 23, url: '/help/stalk' },
          { name: 'viper strike', level: 23, url: '/help/viper-strike' },
          { name: 'latch attack', level: 24, url: '/help/latch-attack' },
          { name: 'nightfist', level: 24, url: '/help/nightfist' },
          {
            name: 'sting of the manticore',
            level: 29,
            url: '/help/sting-of-the-manticore',
          },
        ],
      },
      {
        id: Specs.WAY_SEASONS,
        skills: [
          { name: 'style wyvern', level: 15, url: '/help/styles' },
          { name: 'style python', level: 15, url: '/help/styles' },
          { name: 'calm mind', level: 20, url: '/help/calm-mind' },
          { name: 'sweep kick', level: 21, url: '/help/sweep-kick' },
          { name: 'weapon turn', level: 22, url: '/help/weapon-turn' },
          { name: 'perception', level: 22, url: '/help/perception' },
          {
            name: 'blood of winter ice',
            level: 23,
            url: '/help/blood-of-winter-ice',
          },
          { name: 'latch attack', level: 24, url: '/help/latch-attack' },
          {
            name: 'blood of summer fire',
            level: 25,
            url: '/help/blood-of-summer-fire',
          },
          {
            name: 'fortitude of spring',
            level: 31,
            url: '/help/fortitude-of-spring',
          },
        ],
      },
      {
        id: Specs.WAY_BEASTS,
        skills: [
          { name: 'razorspine', level: 15, url: '/help/razorspine' },
          { name: 'style dragon', level: 15, url: '/help/styles' },
          { name: 'style wyvern', level: 15, url: '/help/styles' },
          { name: 'eagle eye', level: 18, url: '/help/eagle-eye' },
          { name: 'sweep kick', level: 21, url: '/help/sweep-kick' },
          { name: 'dash', level: 21, url: '/help/dash' },
          { name: 'weapon turn', level: 22, url: '/help/weapon-turn' },
          { name: 'cleanse', level: 22, url: '/help/cleanse' },
          { name: 'tiger claw', level: 23, url: '/help/tiger-claw' },
          { name: 'dragon blood', level: 24, url: '/help/dragon-blood' },
          {
            name: 'rage of the wolverine',
            level: 25,
            url: '/help/rage-of-the-wolverine',
          },
          { name: 'dragon punch', level: 27, url: '/help/dragon-punch' },
        ],
      },
    ],
    wayfollowChoices: [
      {
        spec: Specs.WAY_SHADOWS,
        desc: [
          'Silent, unseen killing and quiet extraction',
          'Expert in killing on their own terms',
        ],
        allowedAlignments: [Alignment.EVIL],
      },
      {
        spec: Specs.WAY_BEASTS,
        desc: [
          'Sudden brute force and speed',
          'Train amongst animals of the wild',
        ],
        allowedAlignments: [Alignment.GOOD, Alignment.EVIL],
      },
      {
        spec: Specs.WAY_SEASONS,
        desc: [
          'Path of endurance and dedication',
          'Mind and soul with body to overcome adversity',
        ],
        allowedAlignments: [Alignment.GOOD],
      },
    ],
  },

  [Class.TRANSMUTER]: {
    name: Class.TRANSMUTER,
    title: 'Transmuter',
    slug: 'transmuter',
    description: 'Specialist mages who are masters of alteration magic.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [
      { label: 'magicmajor', url: '/help/magicmajor' },
      { label: 'forms', url: '/help/forms' },
    ],
    weapons: [
      { name: 'dagger', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
    ],
    consumables: [
      { name: 'scrolls', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'staves', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'wands', level: 1, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'meditation', level: 4, url: '/help/meditation' },
      { name: 'haggle', level: 6, url: '/help/haggle' },
      { name: 'trance', level: 8, url: '/help/trance' },
      { name: 'fast healing', level: 10, url: '/help/fast-healing' },
      { name: 'parry', level: 11, url: '/help/parry' },
      { name: 'riding', level: 12, url: '/help/mount-ride-dismount-riding' },
      {
        name: 'mounted spellcasting',
        level: 14,
        url: '/help/mounted-spellcasting',
      },
      { name: 'hand to hand', level: 16, url: '/help/hand-to-hand' },
      { name: 'second attack', level: 19, url: '/help/second-attack' },
      {
        name: 'survival instincts',
        level: 20,
        url: '/help/survival-instincts-instincts',
      },
    ],
    basicSpells: [
      { name: 'armor', level: 1, url: '/help/armor' },
      { name: 'read magic', level: 1, url: '/help/read-magic' },
      { name: 'detect magic', level: 1, url: '/help/detect-magic' },
      { name: 'magic missile', level: 1 },
      { name: 'ventriloquate', level: 1, url: '/help/ventriloquate' },
      {
        name: 'invisibility',
        level: 3,
        url: '/help/invisibility-mass-invis-invis',
      },
      { name: 'detect invis', level: 4, url: '/help/detect-invis' },
      { name: 'faerie fire', level: 5, url: '/help/faerie-fire' },
      { name: 'giant strength', level: 5, url: '/help/giant-strength' },
      { name: 'infravision', level: 6, url: '/help/infravision' },
      { name: 'shield', level: 6, url: '/help/shield' },
      { name: 'fly', level: 7, url: '/help/fly' },
      { name: 'enlarge', level: 7, url: '/help/enlarge-shrink' },
      {
        name: 'dispel magic',
        level: 8,
        url: '/help/cancellation-dispel-magic',
      },
      { name: 'protective shield', level: 9, url: '/help/protective-shield' },
      { name: 'shrink', level: 9, url: '/help/enlarge-shrink' },
      { name: 'identify', level: 10, url: '/help/identify' },
      { name: 'locate object', level: 10, url: '/help/locate-object' },
      { name: 'blink', level: 10, url: '/help/blink' },
      { name: 'haste', level: 11, url: '/help/haste' },
      { name: 'teleport', level: 11, url: '/help/teleport-group-teleport' },
      { name: 'pass door', level: 12, url: '/help/pass-door' },
      { name: 'stoneskin', level: 12, url: '/help/ironskin-stoneskin' },
      {
        name: 'trace teleport',
        level: 13,
        url: '/help/block-teleport-trace-teleport',
      },
      { name: 'faerie fog', level: 14, url: '/help/faerie-fog' },
      { name: 'slow', level: 14, url: '/help/slow' },
      { name: 'dimension door', level: 14, url: '/help/dimension-door' },
      {
        name: 'cancellation',
        level: 15,
        url: '/help/cancellation-dispel-magic',
      },
      { name: 'shapeshift', level: 16, url: '/help/shapeshift' },
      { name: 'drain', level: 16, url: '/help/drain' },
      { name: 'crystalbrittle', level: 17, url: '/help/crystalbrittle' },
      { name: 'word of recall', level: 19, url: '/help/word-of-recall' },
      { name: 'eldritch shield', level: 21, url: '/help/eldritch-shield' },
      { name: 'ironskin', level: 22, url: '/help/ironskin-stoneskin' },
      { name: 'soften', level: 23, url: '/help/soften' },
      { name: 'duo dimension', level: 24, url: '/help/duo-dimension-duo' },
    ],
    specSpells: [
      {
        id: Specs.ABJURATION,
        spells: [
          { name: 'spellturning', level: 29, url: '/help/spellturning' },
          { name: 'paralysis', level: 26, url: '/help/paralysis' },
          { name: 'displacement', level: 25, url: '/help/displacement' },
          {
            name: 'block teleport',
            level: 18,
            url: '/help/block-teleport-trace-teleport',
          },
          { name: 'spiderhands', level: 15, url: '/help/spiderhands' },
          { name: 'astral spell', level: 27, url: '/help/astral-spell' },
          { name: 'harden skin', level: 17, url: '/help/harden-skin' },
          {
            name: 'mana shield',
            level: 24,
            url: '/help/mana-shield-manashield',
          },
        ],
      },
      {
        id: Specs.ALTERATION,
        spells: [
          { name: 'polymorph other', level: 27, url: '/help/polymorph-other' },
          {
            name: 'mana shield',
            level: 24,
            url: '/help/mana-shield-manashield',
          },
        ],
      },
    ],
    specSkills: [
      {
        id: Specs.ABJURATION,
        skills: [
          {
            name: 'speed control',
            level: 21,
            url: '/help/skin-control-speed-control-flight',
          },
          {
            name: 'flight control',
            level: 18,
            url: '/help/skin-control-speed-control-flight',
          },
          {
            name: 'skin control',
            level: 20,
            url: '/help/skin-control-speed-control-flight',
          },
          {
            name: 'phase control',
            level: 22,
            url: '/help/skin-control-speed-control-flight',
          },
        ],
      },
    ],
    magicMajorChoices: [
      {
        spec: Specs.ABJURATION,
        desc: [
          'Requires shapeshifting controls to maintain spells when shapeshifting',
        ],
      },
      {
        spec: Specs.ALTERATION,
        desc: [
          'Gain a major shapeshifting form at higher ranks',
          'Shapeshift without needing to use shape controls',
        ],
      },
    ],
  },

  [Class.INVOKER]: {
    name: Class.INVOKER,
    title: 'Invoker',
    slug: 'invoker',
    description: 'Specialist mages who are masters of energy manipulation.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [],
    weapons: [
      { name: 'dagger', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
    ],
    consumables: [
      { name: 'scrolls', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'staves', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'wands', level: 1, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'spellcraft', level: 1, url: '/help/spellcraft' },
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'meditation', level: 4, url: '/help/meditation' },
      { name: 'haggle', level: 6, url: '/help/haggle' },
      { name: 'trance', level: 8, url: '/help/trance' },
      { name: 'fast healing', level: 10, url: '/help/fast-healing' },
      { name: 'parry', level: 11, url: '/help/parry' },
      { name: 'riding', level: 12, url: '/help/mount-ride-dismount-riding' },
      {
        name: 'mounted spellcasting',
        level: 14,
        url: '/help/mounted-spellcasting',
      },
      { name: 'hand to hand', level: 16, url: '/help/hand-to-hand' },
      { name: 'second attack', level: 19, url: '/help/second-attack' },
    ],
    basicSpells: [
      { name: 'armor', level: 1, url: '/help/armor' },
      { name: 'read magic', level: 1, url: '/help/read-magic' },
      { name: 'detect magic', level: 1, url: '/help/detect-magic' },
      { name: 'magic missile', level: 1, url: '/help/magic-missile' },
      { name: 'ventriloquate', level: 1, url: '/help/ventriloquate' },
      { name: 'faerie fire', level: 3, url: '/help/faerie-fire' },
      { name: 'detect invis', level: 4, url: '/help/detect-invis' },
      { name: 'icicle', level: 5, url: '/help/icicle' },
      { name: 'create spring', level: 6, url: '/help/create-spring' },
      {
        name: 'invisibility',
        level: 6,
        url: '/help/invisibility-mass-invis-invis',
      },
      { name: 'infravision', level: 7, url: '/help/infravision' },
      { name: 'alarm', level: 7, url: '/help/alarm' },
      { name: 'brew', level: 8, url: '/help/brew' },
      { name: 'lightning bolt', level: 8, url: '/help/lightning-bolt' },
      { name: 'earthquake', level: 9, url: '/help/earthquake' },
      { name: 'identify', level: 9, url: '/help/identify' },
      { name: 'shield', level: 9, url: '/help/shield' },
      { name: 'locate object', level: 10, url: '/help/locate-object' },
      { name: 'blink', level: 10, url: '/help/blink' },
      { name: 'protective shield', level: 11, url: '/help/protective-shield' },
      {
        name: 'dispel magic',
        level: 12,
        url: '/help/cancellation-dispel-magic',
      },
      { name: 'fireball', level: 12, url: '/help/fireball' },
      { name: 'fly', level: 12, url: '/help/fly' },
      { name: 'teleport', level: 12, url: '/help/teleport-group-teleport' },
      { name: 'wizard watch', level: 13, url: '/help/wizard-watch' },
      { name: 'faerie fog', level: 14, url: '/help/faerie-fog' },
      { name: 'pass door', level: 15, url: '/help/pass-door' },
      { name: 'mana leech', level: 17, url: '/help/mana-leech' },
      {
        name: 'cancellation',
        level: 20,
        url: '/help/cancellation-dispel-magic',
      },
      { name: 'word of recall', level: 21, url: '/help/word-of-recall' },
    ],
  },

  [Class.NECROMANCER]: {
    name: Class.NECROMANCER,
    title: 'Necromancer',
    slug: 'necromancer',
    description: 'Specialist mages who practice the black magics.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.EVIL],
    reference: [],
    weapons: [
      { name: 'dagger', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'whip', level: 1 },
    ],
    consumables: [
      { name: 'scrolls', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'staves', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'wands', level: 1, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'negative channel', level: 1, url: '/help/negative-channel' },
      { name: 'meditation', level: 5, url: '/help/meditation' },
      { name: 'haggle', level: 7, url: '/help/haggle' },
      { name: 'trance', level: 10, url: '/help/trance' },
      { name: 'parry', level: 11, url: '/help/parry' },
      { name: 'fast healing', level: 12, url: '/help/fast-healing' },
      { name: 'riding', level: 12, url: '/help/mount-ride-dismount-riding' },
      { name: 'embalm', level: 13, url: '/help/embalm' },
      {
        name: 'mounted spellcasting',
        level: 14,
        url: '/help/mounted-spellcasting',
      },
      { name: 'hand to hand', level: 15, url: '/help/hand-to-hand' },
      { name: 'second attack', level: 17, url: '/help/second-attack' },
    ],
    basicSpells: [
      { name: 'read magic', level: 1, url: '/help/read-magic' },
      { name: 'chill touch', level: 1, url: '/help/chill-touch' },
      { name: 'detect magic', level: 1, url: '/help/detect-magic' },
      { name: 'magic missile', level: 1, url: '/help/magic-missile' },
      { name: 'ventriloquate', level: 1, url: '/help/ventriloquate' },
      { name: 'armor', level: 2, url: '/help/armor' },
      { name: 'detect invis', level: 2, url: '/help/detect-invis' },
      { name: 'faerie fire', level: 3, url: '/help/faerie-fire' },
      { name: 'weaken', level: 5, url: '/help/weaken' },
      { name: 'infravision', level: 6, url: '/help/infravision' },
      { name: 'sleep', level: 7, url: '/help/sleep' },
      { name: 'blindness', level: 8, url: '/help/blindness' },
      {
        name: 'mass invis',
        level: 9,
        url: '/help/invisibility-mass-invis-invis',
      },
      { name: 'lesser golem', level: 10, url: '/help/lesser-golem' },
      { name: 'shadowself', level: 10, url: '/help/shadowself' },
      { name: 'preserve', level: 10, url: '/help/preserve' },
      {
        name: 'dispel magic',
        level: 11,
        url: '/help/cancellation-dispel-magic',
      },
      { name: 'poison', level: 11, url: '/help/poison' },
      { name: 'decay corpse', level: 11, url: '/help/decay-corpse' },
      { name: 'acid blast', level: 12, url: '/help/acid-blast' },
      { name: 'identify', level: 12, url: '/help/identify' },
      { name: 'teleport', level: 12, url: '/help/teleport-group-teleport' },
      { name: 'animate skeleton', level: 12, url: '/help/animate-skeleton' },
      { name: 'locate object', level: 13, url: '/help/locate-object' },
      { name: 'protective shield', level: 13, url: '/help/protective-shield' },
      { name: 'curse', level: 14, url: '/help/curse' },
      { name: 'faerie fog', level: 14, url: '/help/faerie-fog' },
      {
        name: 'cancellation',
        level: 15,
        url: '/help/cancellation-dispel-magic',
      },
      { name: 'energy drain', level: 15, url: '/help/energy-drain' },
      { name: 'animate dead', level: 16, url: '/help/animate-dead' },
      { name: 'pass door', level: 16, url: '/help/pass-door' },
      { name: 'crimson scourge', level: 17, url: '/help/crimson-scourge' },
      { name: 'summon', level: 18, url: '/help/summon' },
      { name: 'wraithform', level: 18, url: '/help/wraithform' },
      { name: 'vampiric touch', level: 19, url: '/help/vampiric-touch' },
      { name: 'leech undead', level: 20, url: '/help/leech-undead' },
      { name: 'cone of acid', level: 20, url: '/help/cone-of-acid' },
      { name: 'convocation', level: 20, url: '/help/convocation' },
      { name: 'word of recall', level: 21, url: '/help/word-of-recall' },
      { name: 'ghoul flesh', level: 22, url: '/help/ghoul-flesh' },
      { name: 'iron golem', level: 23, url: '/help/iron-golem' },
      { name: 'disruption', level: 24, url: '/help/disruption' },
      { name: 'mana shield', level: 25, url: '/help/mana-shield-manashield' },
      { name: 'shadowfire', level: 30, url: '/help/shadowfire' },
      { name: 'power word kill', level: 31, url: '/help/power-word-kill' },
    ],
  },

  [Class.OUTCAST]: {
    name: Class.OUTCAST,
    title: 'Outcast',
    slug: 'outcast',
    description:
      'Knight outcasts who turn on good and follow the black magics.',
    features: [],
    xpPenalty: 15,
    allowedAlignments: [Alignment.EVIL],
    reference: [],
    weapons: [
      { name: 'axe', level: 1 },
      { name: 'dagger', level: 1 },
      { name: 'flail', level: 1 },
      { name: 'mace', level: 1 },
      { name: 'polearm', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'bow', level: 1 },
      { name: 'crossbow', level: 1 },
    ],
    basicSkills: [
      { name: 'shield block', level: 1, url: '/help/shield-block' },
      { name: 'enhanced damage', level: 1, url: '/help/enhanced-damage' },
      { name: 'parry', level: 1, url: '/help/parry' },
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'dirt kicking', level: 2, url: '/help/dirt-dirt-kicking' },
      { name: 'kick', level: 4, url: '/help/kick' },
      { name: 'second attack', level: 5, url: '/help/second-attack' },
      { name: 'fast healing', level: 6, url: '/help/fast-healing' },
      { name: 'haggle', level: 6, url: '/help/haggle' },
      { name: 'trip', level: 7, url: '/help/trip' },
      { name: 'disarm', level: 8, url: '/help/disarm' },
      { name: 'hand to hand', level: 9, url: '/help/hand-to-hand' },
      { name: 'bash', level: 10, url: '/help/bash' },
      { name: 'riding', level: 10, url: '/help/mount-ride-dismount-riding' },
      { name: 'dual wield', level: 11, url: '/help/dual-dual-wield' },
      {
        name: 'third attack',
        level: 11,
        url: '/help/third-attack-fourth-attack',
      },
      { name: 'meditation', level: 12, url: '/help/meditation' },
      { name: 'shield cleave', level: 13, url: '/help/shield-cleave' },
      { name: 'lore', level: 14, url: '/help/lore' },
      { name: 'lunge', level: 14, url: '/help/lunge' },
      { name: 'stance', level: 15, url: '/help/stance-stances-relax' },
      { name: 'mounted fighting', level: 15, url: '/help/mounted-fighting' },
      { name: 'crucify', level: 16, url: '/help/crucify' },
      { name: 'shove', level: 18, url: '/help/shove' },
      { name: 'brutal block', level: 19, url: '/help/brutal-block' },
      { name: 'break weapon', level: 21, url: '/help/break-weapon' },
      { name: 'shield bash', level: 21, url: '/help/shield-bash' },
      {
        name: 'mounted spellcasting',
        level: 22,
        url: '/help/mounted-spellcasting',
      },
      { name: 'demand', level: 24, url: '/help/demand' },
      { name: 'cross slice', level: 25, url: '/help/cross-slice-crossslice' },
      { name: 'cleave', level: 26, url: '/help/cleave' },
      { name: 'warrior spirit', level: 26, url: '/help/warrior-spirit' },
      { name: 'slaughter', level: 31, url: '/help/slaughter' },
    ],
    basicSpells: [
      { name: 'magic missile', level: 1 },
      { name: 'chill touch', level: 2, url: '/help/chill-touch' },
      { name: 'acid arrow', level: 3, url: '/help/acid-arrow' },
      { name: 'blindness', level: 4, url: '/help/blindness' },
      { name: 'poison', level: 5, url: '/help/poison' },
      { name: 'curse', level: 6, url: '/help/curse' },
      {
        name: 'invisibility',
        level: 6,
        url: '/help/invisibility-mass-invis-invis',
      },
      { name: 'detect invis', level: 7, url: '/help/detect-invis' },
      { name: 'protection', level: 7, url: '/help/protection' },
      { name: 'lightning bolt', level: 8 },
      { name: 'teleport', level: 9, url: '/help/teleport-group-teleport' },
      { name: 'energy drain', level: 13, url: '/help/energy-drain' },
      { name: 'summon', level: 16, url: '/help/summon' },
      { name: 'plague', level: 17, url: '/help/plague' },
      { name: 'sleep', level: 19, url: '/help/sleep' },
      { name: 'hail of stones', level: 20, url: '/help/hail-of-stones' },
      { name: 'accursed gaeas', level: 22, url: '/help/accursed-gaeas' },
      { name: 'enslave', level: 23, url: '/help/enslave' },
      { name: 'hell ball', level: 24, url: '/help/hell-ball' },
      { name: 'corrupt object', level: 28, url: '/help/corrupt-object' },
    ],
  },
};

// Helper function to get class by name
export function getClass(name: Class | string): ClassData | undefined {
  return classes[name as Class];
}

// Helper function to get class by slug
export function getClassBySlug(slug: string): ClassData | undefined {
  return Object.values(classes).find(cls => cls.slug === slug);
}

// Helper function to get all classes
export function getAllClasses(): ClassData[] {
  return Object.values(classes);
}

// Helper function to get classes by alignment
export function getClassesByAlignment(alignment: Alignment): ClassData[] {
  return Object.values(classes).filter(cls =>
    cls.allowedAlignments.includes(alignment)
  );
}
