import { ClassData } from './types';
import { Class, Alignment, Specs } from './enums';

export const classes: Record<Class, ClassData> = {
  [Class.FIGHTER]: {
    name: Class.FIGHTER,
    title: 'Fighter',
    slug: 'fighter',
    description: 'Best all around fighters, little magic ability.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [
      { label: 'specialization', url: '/help/specialization-specialize' },
    ],
    consumables: [],
    weapons: [
      { name: 'axe', level: 1 },
      { name: 'dagger', level: 1 },
      { name: 'flail', level: 1 },
      { name: 'mace', level: 1 },
      { name: 'polearm', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
      { name: 'bow', level: 1 },
      { name: 'crossbow', level: 1 },
    ],
    basicSkills: [
      { name: 'shield block', level: 1, url: '/help/shield-block' },
      { name: 'enhanced damage', level: 1, url: '/help/enhanced-damage' },
      { name: 'rescue', level: 1, url: '/help/rescue' },
      { name: 'parry', level: 1, url: '/help/parry' },
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'dirt kicking', level: 2, url: '/help/dirt-dirt-kicking' },
      { name: 'hand to hand', level: 3, url: '/help/hand-to-hand' },
      { name: 'kick', level: 3, url: '/help/kick' },
      { name: 'second attack', level: 4, url: '/help/second-attack' },
      { name: 'fast healing', level: 5, url: '/help/fast-healing' },
      { name: 'trip', level: 6, url: '/help/trip' },
      { name: 'feint', level: 7, url: '/help/feint' },
      { name: 'bandage', level: 8, url: '/help/bandage' },
      { name: 'warcry', level: 9, url: '/help/warcry' },
      { name: 'disarm', level: 9, url: '/help/disarm' },
      { name: 'dual wield', level: 10, url: '/help/dual-dual-wield' },
      { name: 'dodge', level: 10, url: '/help/dodge' },
      { name: 'riding', level: 10, url: '/help/mount-ride-dismount-riding' },
      { name: 'bash', level: 11, url: '/help/bash' },
      { name: 'third attack', level: 11, url: '/help/third-attack-fourth-attack' },
      { name: 'berserk', level: 12, url: '/help/berserk' },
      { name: 'haggle', level: 12, url: '/help/haggle-haggling' },
      { name: 'meditation', level: 12, url: '/help/meditation' },
      { name: 'shield cleave', level: 13, url: '/help/shield-cleave' },
      { name: 'stance', level: 13, url: '/help/stance-stances-relax' },
      { name: 'lunge', level: 14, url: '/help/lunge' },
      { name: 'trophy', level: 14, url: '/help/trophy' },
      { name: 'crush', level: 15, url: '/help/crush' },
      { name: 'lore', level: 16, url: '/help/lore' },
      { name: 'offhand disarm', level: 16, url: '/help/offhand-disarm' },
      { name: 'mounted fighting', level: 16, url: '/help/mounted-fighting' },
      { name: 'recovery', level: 17, url: '/help/recovery' },
      { name: 'toughen', level: 20, url: '/help/toughen' },
      { name: 'warrior spirit', level: 21, url: '/help/warrior-spirit' },
      { name: 'fourth attack', level: 23, url: '/help/third-attack-fourth-attack' },
      { name: 'adrenalin rush', level: 25, url: '/help/adrenalin-rush' },
    ],
    specChoices: 3,
    specAllowed: [
      Specs.SWORD,
      Specs.DAGGER,
      Specs.WHIP_FLAIL,
      Specs.MACE,
      Specs.AXE,
      Specs.STAFF,
      Specs.SPEAR,
      Specs.HAND_TO_HAND,
      Specs.RANGED,
      Specs.SHIELD,
    ],
    specSkills: [
      {
        id: Specs.SWORD,
        skills: [
          { name: 'flurry', level: 29, url: '/help/flurry' },
          { name: 'flourentine', level: 18, url: '/help/flourentine' },
          { name: 'riposte', level: 21, url: '/help/riposte' },
          { name: 'cross slice', level: 22, url: '/help/cross-slice-crossslice' },
        ],
      },
      {
        id: Specs.DAGGER,
        skills: [
          { name: 'undercut', level: 19, url: '/help/undercut' },
          { name: 'bleed', level: 14, url: '/help/bleed' },
          { name: 'restrike', level: 24, url: '/help/restrike' },
        ],
      },
      {
        id: Specs.WHIP_FLAIL,
        skills: [
          { name: 'flog', level: 16, url: '/help/flog-flogging' },
          { name: 'strip weapon', level: 16, url: '/help/strip-weapon' },
          { name: 'choke', level: 21, url: '/help/choke' },
          { name: 'lash', level: 11, url: '/help/lash' },
          { name: 'pull', level: 19, url: '/help/pull' },
          { name: 'eyejab', level: 13, url: '/help/eyejab' },
        ],
      },
      {
        id: Specs.MACE,
        skills: [
          { name: 'boneshatter', level: 17, url: '/help/boneshatter' },
          { name: 'backhand', level: 15, url: '/help/backhand' },
          { name: 'drumming maces', level: 26, url: '/help/drumming-maces-drum' },
        ],
      },
      {
        id: Specs.AXE,
        skills: [
          { name: 'pincer', level: 21, url: '/help/pincer' },
          { name: 'cleave', level: 26, url: '/help/cleave' },
          { name: 'chop', level: 14, url: '/help/chop' },
          { name: 'concussion strike', level: 23, url: '/help/concussion-strike-concussion' },
          { name: 'wrist chop', level: 26, url: '/help/wrist-chop-wristchop' },
          { name: 'meatgrinder', level: 28, url: '/help/meatgrinder' },
        ],
      },
      {
        id: Specs.STAFF,
        skills: [
          { name: 'overhead', level: 20, url: '/help/overhead' },
          { name: 'pugil', level: 10, url: '/help/pugil' },
          { name: 'leg sweep', level: 16, url: '/help/leg-sweep-legsweep' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
        ],
      },
      {
        id: Specs.SPEAR,
        skills: [
          { name: 'charge set', level: 22, url: '/help/charge-set' },
          { name: 'impale', level: 26, url: '/help/impale' },
          { name: 'jab', level: 16, url: '/help/jab' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
          { name: 'harpoon', level: 31, url: '/help/harpoon' },
        ],
      },
      {
        id: Specs.HAND_TO_HAND,
        skills: [
          { name: 'iron strike', level: 11, url: '/help/iron-strike-ironstrike' },
          { name: 'throw', level: 16, url: '/help/throw' },
          { name: 'leaping strike', level: 20, url: '/help/leaping-strike' },
          { name: 'ground control', level: 18, url: '/help/ground-control' },
          { name: 'hand block', level: 12, url: '/help/hand-block' },
          { name: 'grapple', level: 10, url: '/help/grapple-grappling' },
        ],
      },
      {
        id: Specs.RANGED,
        skills: [
          { name: 'accuracy', level: 11, url: '/help/accuracy' },
          { name: 'quick shot', level: 15, url: '/help/quick-shot-quickshot' },
          { name: 'aimed shot', level: 19, url: '/help/aimed-shot' },
          { name: 'volley', level: 26, url: '/help/volley' },
        ],
      },
      {
        id: Specs.SHIELD,
        skills: [
          { name: 'shield mastery', level: 24, url: '/help/shield-mastery' },
          { name: 'shield bash', level: 21, url: '/help/shield-bash' },
          { name: 'porcupine stance', level: 16, url: '/help/porcupine-stance' },
        ],
      },
    ],
  },

  [Class.KNIGHT]: {
    name: Class.KNIGHT,
    title: 'Knight',
    slug: 'knight',
    description: 'Seekers of full knighthood.',
    features: [],
    xpPenalty: 20,
    allowedAlignments: [Alignment.GOOD],
    reference: [],
    weapons: [
      { name: 'axe', level: 1 },
      { name: 'mace', level: 1 },
      { name: 'polearm', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'staff', level: 1 },
      { name: 'bow', level: 1 },
      { name: 'crossbow', level: 1 },
    ],
    consumables: [
      { name: 'scrolls', level: 2, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'shield block', level: 3, url: '/help/shield-block' },
      { name: 'kick', level: 3, url: '/help/kick' },
      { name: 'rescue', level: 5, url: '/help/rescue' },
      { name: 'parry', level: 5, url: '/help/parry' },
      { name: 'enhanced damage', level: 6, url: '/help/enhanced-damage' },
      { name: 'hand to hand', level: 6, url: '/help/hand-to-hand' },
      { name: 'fast healing', level: 6, url: '/help/fast-healing' },
      { name: 'meditation', level: 7, url: '/help/meditation' },
      { name: 'second attack', level: 8, url: '/help/second-attack' },
      { name: 'riding', level: 8, url: '/help/mount-ride-dismount-riding' },
      { name: 'bash', level: 9, url: '/help/bash' },
      { name: 'pugil', level: 10, url: '/help/pugil' },
      { name: 'lore', level: 11, url: '/help/lore' },
      { name: 'disarm', level: 12, url: '/help/disarm' },
      { name: 'dual wield', level: 14, url: '/help/dual-dual-wield' },
      { name: 'lunge', level: 14, url: '/help/lunge' },
      { name: 'mounted fighting', level: 14, url: '/help/mounted-fighting' },
      { name: 'shield cleave', level: 15, url: '/help/shield-cleave' },
      { name: 'stance', level: 15, url: '/help/stance-stances-relax' },
      { name: 'leadership', level: 15, url: '/help/leadership' },
      { name: 'third attack', level: 16, url: '/help/third-attack-fourth-attack' },
      { name: 'ceremonial burial', level: 17, url: '/help/ceremonial-burial' },
      { name: 'stand off', level: 17, url: '/help/stand-off' },
      { name: 'flank', level: 18, url: '/help/flanking' },
      { name: 'laying hands', level: 19, url: '/help/laying-hands' },
      { name: 'righteous warfare', level: 20, url: '/help/righteous-warfare' },
      { name: 'cross block', level: 20, url: '/help/cross-block' },
      { name: 'spike', level: 21, url: '/help/spike' },
      { name: 'riposte', level: 21, url: '/help/riposte' },
      { name: 'shield bash', level: 21, url: '/help/shield-bash' },
      { name: 'overhead', level: 22, url: '/help/overhead' },
      { name: 'backhand', level: 22, url: '/help/backhand' },
      { name: 'charge set', level: 23, url: '/help/charge-set' },
      { name: 'divine health', level: 24, url: '/help/divine-health' },
      { name: 'cross slice', level: 25, url: '/help/cross-slice-crossslice' },
      { name: 'warrior spirit', level: 26, url: '/help/warrior-spirit' },
      { name: 'impale', level: 27, url: '/help/impale' },
      { name: 'aura of courage', level: 29, url: '/help/aura-of-courage' },
      { name: 'spiritual healing', level: 33, url: '/help/spiritual-healing' },
    ],
    basicSpells: [
      { name: 'armor', level: 2, url: '/help/armor' },
      { name: 'cure light', level: 2, url: '/help/cure-light' },
      { name: 'bless', level: 4, url: '/help/bless' },
      { name: 'create food', level: 4, url: '/help/create-food' },
      { name: 'refresh', level: 4, url: '/help/refresh' },
      { name: 'cure serious', level: 5, url: '/help/cure-serious' },
      { name: 'detect evil', level: 5, url: '/help/detect-evil' },
      { name: 'protection', level: 5, url: '/help/protection' },
      { name: 'create water', level: 6, url: '/help/create-water' },
      { name: 'dispel evil', level: 7, url: '/help/dispel-evil' },
      { name: 'detect invis', level: 8, url: '/help/detect-invis' },
      { name: 'cure critical', level: 9, url: '/help/cure-critical' },
      { name: 'create spring', level: 11, url: '/help/create-spring' },
      { name: 'flamestrike', level: 12, url: '/help/flamestrike' },
      { name: 'wrath', level: 16, url: '/help/wrath-vengeance' },
      { name: 'calm', level: 17, url: '/help/calm' },
      { name: 'frenzy', level: 18, url: '/help/frenzy' },
      { name: 'summon', level: 18, url: '/help/summon' },
      { name: 'banishment', level: 19, url: '/help/banishment' },
      { name: 'lightshield', level: 20, url: '/help/lightshield' },
      { name: 'turn undead', level: 21, url: '/help/turn-undead' },
      { name: 'word of recall', level: 22, url: '/help/word-of-recall' },
      { name: 'protectorate', level: 23, url: '/help/protectorate' },
      { name: 'holy prayer', level: 24, url: '/help/holy-prayer' },
      { name: 'shield of faith', level: 28, url: '/help/shield-of-faith' },
      { name: 'sanctify object', level: 30, url: '/help/sanctify-object' },
      { name: 'templars sight', level: 32, url: '/help/templars-sight' },
    ],
  },

  [Class.RANGER]: {
    name: Class.RANGER,
    title: 'Ranger',
    slug: 'ranger',
    description: 'Forest warriors, learned in woodlore and survival.',
    features: [],
    xpPenalty: 10,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL],
    reference: [
      { label: 'specialization', url: '/help/specialization-specialize' },
    ],
    weapons: [
      { name: 'axe', level: 1 },
      { name: 'dagger', level: 1 },
      { name: 'flail', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
      { name: 'bow', level: 1 },
      { name: 'crossbow', level: 1 },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'bash', level: 2, url: '/help/bash' },
      { name: 'dirt kicking', level: 2, url: '/help/dirt-dirt-kicking' },
      { name: 'quiet movement', level: 3, url: '/help/quiet-movement' },
      { name: 'parry', level: 3, url: '/help/parry' },
      { name: 'butcher', level: 4, url: '/help/butcher' },
      { name: 'acute vision', level: 5, url: '/help/camouflage-acute-vision' },
      { name: 'pathfinding', level: 5 },
      { name: 'hand to hand', level: 6, url: '/help/hand-to-hand' },
      { name: 'second attack', level: 7, url: '/help/second-attack' },
      { name: 'riding', level: 7, url: '/help/mount-ride-dismount-riding' },
      { name: 'camouflage', level: 8, url: '/help/camouflage-acute-vision' },
      { name: 'herb', level: 8, url: '/help/herbs-curative-herbs' },
      { name: 'enhanced damage', level: 9, url: '/help/enhanced-damage' },
      { name: 'meditation', level: 9, url: '/help/meditation' },
      { name: 'find water', level: 10, url: '/help/find-water' },
      { name: 'ambush', level: 10, url: '/help/ambush' },
      { name: 'fast healing', level: 11, url: '/help/fast-healing' },
      { name: 'skin', level: 11 },
      { name: 'dodge', level: 12, url: '/help/dodge' },
      { name: 'snare', level: 12, url: '/help/snare' },
      { name: 'mounted fighting', level: 12, url: '/help/mounted-fighting' },
      { name: 'lore', level: 13, url: '/help/lore' },
      { name: 'dual wield', level: 13, url: '/help/dual-dual-wield' },
      { name: 'ranger ammo', level: 13, url: '/help/ranger-ammo-rangerammo' },
      { name: 'protection heat cold', level: 14, url: '/help/protection-heat-cold' },
      { name: 'camp', level: 14, url: '/help/camp' },
      { name: 'stance', level: 14, url: '/help/stance-stances-relax' },
      { name: 'shield block', level: 15, url: '/help/shield-block' },
      { name: 'curative herbs', level: 15, url: '/help/herbs-curative-herbs' },
      { name: 'third attack', level: 16, url: '/help/third-attack-fourth-attack' },
      { name: 'barkskin', level: 17, url: '/help/barkskin' },
      { name: 'flank', level: 17, url: '/help/flanking' },
      { name: 'animal call', level: 18, url: '/help/animal-call' },
      { name: 'ranger staff', level: 19, url: '/help/ranger-staff' },
      { name: 'moving ambush', level: 20, url: '/help/moving-ambush' },
      { name: 'wilderness familiarity', level: 21, url: '/help/wilderness-familiarity' },
      { name: 'tailored skins', level: 22, url: '/help/tailored-skins-tailor-skins' },
      { name: 'creep', level: 23, url: '/help/creep' },
      { name: 'hunt', level: 25, url: '/help/hunt' },
      { name: 'forest guardianship', level: 26, url: '/help/forest-guardianship-guardianship' },
      { name: 'warrior spirit', level: 26, url: '/help/warrior-spirit' },
    ],
    specChoices: 2,
    specAllowed: [
      Specs.WHIP_FLAIL,
      Specs.STAFF,
      Specs.RANGED,
      Specs.AXE,
      Specs.HAND_TO_HAND,
      Specs.SPEAR,
    ],
    specSkills: [
      {
        id: Specs.STAFF,
        skills: [
          { name: 'overhead', level: 20, url: '/help/overhead' },
          { name: 'pugil', level: 10, url: '/help/pugil' },
          { name: 'leg sweep', level: 16, url: '/help/leg-sweep-legsweep' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
        ],
      },
      {
        id: Specs.RANGED,
        skills: [
          { name: 'accuracy', level: 11, url: '/help/accuracy' },
          { name: 'quick shot', level: 15, url: '/help/quick-shot-quickshot' },
          { name: 'aimed shot', level: 19, url: '/help/aimed-shot' },
          { name: 'volley', level: 26, url: '/help/volley' },
        ],
      },
      {
        id: Specs.AXE,
        skills: [
          { name: 'pincer', level: 21, url: '/help/pincer' },
          { name: 'cleave', level: 26, url: '/help/cleave' },
          { name: 'chop', level: 14, url: '/help/chop' },
          { name: 'concussion strike', level: 23, url: '/help/concussion-strike-concussion' },
          { name: 'wrist chop', level: 26, url: '/help/wrist-chop-wristchop' },
          { name: 'meatgrinder', level: 28, url: '/help/meatgrinder' },
        ],
      },
      {
        id: Specs.SPEAR,
        skills: [
          { name: 'charge set', level: 22, url: '/help/charge-set' },
          { name: 'impale', level: 26, url: '/help/impale' },
          { name: 'jab', level: 16, url: '/help/jab' },
          { name: 'stand off', level: 15, url: '/help/stand-off' },
          { name: 'harpoon', level: 31, url: '/help/harpoon' },
        ],
      },
      {
        id: Specs.WHIP_FLAIL,
        skills: [
          { name: 'flog', level: 16, url: '/help/flog-flogging' },
          { name: 'strip weapon', level: 16, url: '/help/strip-weapon' },
          { name: 'choke', level: 21, url: '/help/choke' },
          { name: 'lash', level: 11, url: '/help/lash' },
          { name: 'pull', level: 19, url: '/help/pull' },
          { name: 'eyejab', level: 13, url: '/help/eyejab' },
        ],
      },
      {
        id: Specs.HAND_TO_HAND,
        skills: [
          { name: 'iron strike', level: 11, url: '/help/iron-strike-ironstrike' },
          { name: 'throw', level: 16, url: '/help/throw' },
          { name: 'leaping strike', level: 20, url: '/help/leaping-strike' },
          { name: 'ground control', level: 18, url: '/help/ground-control' },
          { name: 'hand block', level: 12, url: '/help/hand-block' },
          { name: 'grapple', level: 10, url: '/help/grapple-grappling' },
        ],
      },
    ],
  },
  [Class.CLERIC]: {
    name: Class.CLERIC,
    title: 'Cleric',
    slug: 'cleric',
    description: 'Followers of the Gods.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [{ label: 'worship', url: '/help/worship' }],
  },

  [Class.DRUID]: {
    name: Class.DRUID,
    title: 'Druid',
    slug: 'druid',
    description: 'Disciples of natural magic and control.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL],
    reference: [{ label: 'kinship', url: '/help/animal-kinship-kinship' }],
  },

  [Class.THIEF]: {
    name: Class.THIEF,
    title: 'Thief',
    slug: 'thief',
    description: "The skilled stealer of other people's belongings.",
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [],
  },

  [Class.ASSASSIN]: {
    name: Class.ASSASSIN,
    title: 'Assassin',
    slug: 'assassin',
    description: 'Specialists in stealth and unarmed killing.',
    features: [],
    xpPenalty: 15,
    allowedAlignments: [Alignment.GOOD, Alignment.EVIL],
    reference: [{ label: 'wayfollow', url: '/help/wayfollow-waypath' }],
    weapons: [
      { name: 'dagger', level: 1 },
      { name: 'spear', level: 1 },
      { name: 'sword', level: 1 },
      { name: 'staff', level: 1 },
    ],
    consumables: [
      { name: 'staves', level: 1, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'dodge', level: 1, url: '/help/dodge' },
      { name: 'hand to hand', level: 1, url: '/help/hand-to-hand' },
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'dirt kicking', level: 2, url: '/help/dirt-dirt-kicking' },
      { name: 'trip', level: 3, url: '/help/trip' },
      { name: 'enhanced damage', level: 4, url: '/help/enhanced-damage' },
      { name: 'kick', level: 4, url: '/help/kick' },
      { name: 'meditation', level: 5, url: '/help/meditation' },
      { name: 'sneak', level: 5, url: '/help/sneak' },
      { name: 'haggle', level: 6, url: '/help/haggle' },
      { name: 'hide', level: 6, url: '/help/hide' },
      { name: 'hand block', level: 7, url: '/help/hand-block' },
      { name: 'detect hidden', level: 8, url: '/help/detect-hidden' },
      { name: 'second attack', level: 8, url: '/help/second-attack' },
      { name: 'parry', level: 9, url: '/help/parry' },
      { name: 'fast healing', level: 9, url: '/help/fast-healing' },
      { name: 'riding', level: 9, url: '/help/mount-ride-dismount-riding' },
      { name: 'caltraps', level: 10, url: '/help/caltraps' },
      { name: 'endure', level: 10, url: '/help/endure' },
      { name: 'disarm', level: 10, url: '/help/disarm' },
      { name: 'nerve', level: 11, url: '/help/nerve' },
      { name: 'follow through', level: 11, url: '/help/follow-through' },
      { name: 'bash', level: 11, url: '/help/bash' },
      { name: 'dual wield', level: 12, url: '/help/dual-dual-wield' },
      { name: 'pick lock', level: 12, url: '/help/pick-lock' },
      { name: 'attack of opportunity', level: 12, url: '/help/attack-of-opportunity' },
      { name: 'lore', level: 13, url: '/help/lore' },
      { name: 'throw', level: 13, url: '/help/throw' },
      { name: 'vanish', level: 13, url: '/help/vanish' },
      { name: 'poison dust', level: 14, url: '/help/poison-dust' },
      { name: 'style tiger', level: 14, url: '/help/styles' },
      { name: 'recovery', level: 14, url: '/help/recovery' },
      { name: 'shield block', level: 15, url: '/help/shield-block' },
      { name: 'iron strike', level: 15, url: '/help/iron-strike-ironstrike' },
      { name: 'mounted fighting', level: 15, url: '/help/mounted-fighting' },
      { name: 'shuriken', level: 16, url: '/help/shuriken' },
      { name: 'blindness dust', level: 16, url: '/help/blindness-dust' },
      { name: 'third attack', level: 16, url: '/help/third-attack-fourth-attack' },
      { name: 'strangle', level: 17, url: '/help/strangle' },
      { name: 'leaping strike', level: 18, url: '/help/leaping-strike' },
      { name: 'ground control', level: 19, url: '/help/ground-control' },
      { name: 'find vulnerability', level: 21, url: '/help/find-vulnerability' },
      { name: 'assassinate', level: 26, url: '/help/assassinate' },
    ],
    basicSpells: [
      { name: 'invisibility', level: 7, url: '/help/invisibility' },
      { name: 'infravision', level: 9, url: '/help/infravision' },
      { name: 'detect invis', level: 10, url: '/help/detect-invisibility' },
      { name: 'locate object', level: 17, url: '/help/locate-object' },
    ],
    specSpells: [
      {
        id: Specs.WAY_SHADOWS,
        spells: [
          { name: 'word of recall', level: 21, url: '/help/word-of-recall' },
        ],
      },
    ],
    specSkills: [
      {
        id: Specs.WAY_SHADOWS,
        skills: [
          { name: 'style python', level: 15, url: '/help/styles' },
          { name: 'style viper', level: 15, url: '/help/styles' },
          { name: 'kidnap', level: 16, url: '/help/kidnap' },
          { name: 'stalk', level: 23, url: '/help/stalk' },
          { name: 'viper strike', level: 23, url: '/help/viper-strike' },
          { name: 'latch attack', level: 24, url: '/help/latch-attack' },
          { name: 'nightfist', level: 24, url: '/help/nightfist' },
          { name: 'sting of the manticore', level: 29, url: '/help/sting-of-the-manticore' },
        ],
      },
      {
        id: Specs.WAY_SEASONS,
        skills: [
          { name: 'style wyvern', level: 15, url: '/help/styles' },
          { name: 'style python', level: 15, url: '/help/styles' },
          { name: 'calm mind', level: 20, url: '/help/calm-mind' },
          { name: 'sweep kick', level: 21, url: '/help/sweep-kick' },
          { name: 'weapon turn', level: 22, url: '/help/weapon-turn' },
          { name: 'perception', level: 22, url: '/help/perception' },
          { name: 'blood of winter ice', level: 23, url: '/help/blood-of-winter-ice' },
          { name: 'latch attack', level: 24, url: '/help/latch-attack' },
          { name: 'blood of summer fire', level: 25, url: '/help/blood-of-summer-fire' },
          { name: 'fortitude of spring', level: 31, url: '/help/fortitude-of-spring' },
        ],
      },
      {
        id: Specs.WAY_BEASTS,
        skills: [
          { name: 'razorspine', level: 15, url: '/help/razorspine' },
          { name: 'style dragon', level: 15, url: '/help/styles' },
          { name: 'style wyvern', level: 15, url: '/help/styles' },
          { name: 'eagle eye', level: 18, url: '/help/eagle-eye' },
          { name: 'sweep kick', level: 21, url: '/help/sweep-kick' },
          { name: 'dash', level: 21, url: '/help/dash' },
          { name: 'weapon turn', level: 22, url: '/help/weapon-turn' },
          { name: 'cleanse', level: 22, url: '/help/cleanse' },
          { name: 'tiger claw', level: 23, url: '/help/tiger-claw' },
          { name: 'dragon blood', level: 24, url: '/help/dragon-blood' },
          { name: 'rage of the wolverine', level: 25, url: '/help/rage-of-the-wolverine' },
          { name: 'dragon punch', level: 27, url: '/help/dragon-punch' },
        ],
      },
    ],
    wayfollowChoices: [
      {
        spec: Specs.WAY_SHADOWS,
        desc: [
          'Silent, unseen killing and quiet extraction',
          'Expert in killing on their own terms',
        ],
        allowedAlignments: [Alignment.EVIL],
      },
      {
        spec: Specs.WAY_BEASTS,
        desc: [
          'Sudden brute force and speed',
          'Train amongst animals of the wild',
        ],
        allowedAlignments: [Alignment.GOOD, Alignment.EVIL],
      },
      {
        spec: Specs.WAY_SEASONS,
        desc: [
          'Path of endurance and dedication',
          'Mind and soul with body to overcome adversity',
        ],
        allowedAlignments: [Alignment.GOOD],
      },
    ],
  },

  [Class.TRANSMUTER]: {
    name: Class.TRANSMUTER,
    title: 'Transmuter',
    slug: 'transmuter',
    description: 'Specialist mages who are masters of alteration magic.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [
      { label: 'magicmajor', url: '/help/magicmajor' },
      { label: 'forms', url: '/help/forms' },
    ],
    weapons: [
      { name: 'dagger', level: 1 },
      { name: 'whip', level: 1 },
      { name: 'staff', level: 1 },
    ],
    consumables: [
      { name: 'scrolls', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'staves', level: 1, url: '/help/brandish-quaff-recite-zap' },
      { name: 'wands', level: 1, url: '/help/brandish-quaff-recite-zap' },
    ],
    basicSkills: [
      { name: 'recall', level: 1, url: '/help/recall-' },
      { name: 'meditation', level: 4, url: '/help/meditation' },
      { name: 'haggle', level: 6, url: '/help/haggle' },
      { name: 'trance', level: 8, url: '/help/trance' },
      { name: 'fast healing', level: 10, url: '/help/fast-healing' },
      { name: 'parry', level: 11, url: '/help/parry' },
      { name: 'riding', level: 12, url: '/help/mount-ride-dismount-riding' },
      { name: 'mounted spellcasting', level: 14, url: '/help/mounted-spellcasting' },
      { name: 'hand to hand', level: 16, url: '/help/hand-to-hand' },
      { name: 'second attack', level: 19, url: '/help/second-attack' },
      { name: 'survival instincts', level: 20, url: '/help/survival-instincts-instincts' },
    ],
    basicSpells: [
      { name: 'armor', level: 1, url: '/help/armor' },
      { name: 'read magic', level: 1, url: '/help/read-magic' },
      { name: 'detect magic', level: 1, url: '/help/detect-magic' },
      { name: 'magic missile', level: 1 },
      { name: 'ventriloquate', level: 1, url: '/help/ventriloquate' },
      { name: 'invisibility', level: 3, url: '/help/invisibility-mass-invis-invis' },
      { name: 'detect invis', level: 4, url: '/help/detect-invis' },
      { name: 'faerie fire', level: 5, url: '/help/faerie-fire' },
      { name: 'giant strength', level: 5, url: '/help/giant-strength' },
      { name: 'infravision', level: 6, url: '/help/infravision' },
      { name: 'shield', level: 6, url: '/help/shield' },
      { name: 'fly', level: 7, url: '/help/fly' },
      { name: 'enlarge', level: 7, url: '/help/enlarge-shrink' },
      { name: 'dispel magic', level: 8, url: '/help/cancellation-dispel-magic' },
      { name: 'protective shield', level: 9, url: '/help/protective-shield' },
      { name: 'shrink', level: 9, url: '/help/enlarge-shrink' },
      { name: 'identify', level: 10, url: '/help/identify' },
      { name: 'locate object', level: 10, url: '/help/locate-object' },
      { name: 'blink', level: 10, url: '/help/blink' },
      { name: 'haste', level: 11, url: '/help/haste' },
      { name: 'teleport', level: 11, url: '/help/teleport-group-teleport' },
      { name: 'pass door', level: 12, url: '/help/pass-door' },
      { name: 'stoneskin', level: 12, url: '/help/ironskin-stoneskin' },
      { name: 'trace teleport', level: 13, url: '/help/block-teleport-trace-teleport' },
      { name: 'faerie fog', level: 14, url: '/help/faerie-fog' },
      { name: 'slow', level: 14, url: '/help/slow' },
      { name: 'dimension door', level: 14, url: '/help/dimension-door' },
      { name: 'cancellation', level: 15, url: '/help/cancellation-dispel-magic' },
      { name: 'shapeshift', level: 16, url: '/help/shapeshift' },
      { name: 'drain', level: 16, url: '/help/drain' },
      { name: 'crystalbrittle', level: 17, url: '/help/crystalbrittle' },
      { name: 'word of recall', level: 19, url: '/help/word-of-recall' },
      { name: 'eldritch shield', level: 21, url: '/help/eldritch-shield' },
      { name: 'ironskin', level: 22, url: '/help/ironskin-stoneskin' },
      { name: 'soften', level: 23, url: '/help/soften' },
      { name: 'duo dimension', level: 24, url: '/help/duo-dimension-duo' },
    ],
    specSpells: [
      {
        id: Specs.ABJURATION,
        spells: [
          { name: 'spellturning', level: 29, url: '/help/spellturning' },
          { name: 'paralysis', level: 26, url: '/help/paralysis' },
          { name: 'displacement', level: 25, url: '/help/displacement' },
          { name: 'block teleport', level: 18, url: '/help/block-teleport-trace-teleport' },
          { name: 'spiderhands', level: 15, url: '/help/spiderhands' },
          { name: 'astral spell', level: 27, url: '/help/astral-spell' },
          { name: 'harden skin', level: 17, url: '/help/harden-skin' },
          { name: 'mana shield', level: 24, url: '/help/mana-shield-manashield' },
        ],
      },
      {
        id: Specs.ALTERATION,
        spells: [
          { name: 'polymorph other', level: 27, url: '/help/polymorph-other' },
          { name: 'mana shield', level: 24, url: '/help/mana-shield-manashield' },
        ],
      },
    ],
    specSkills: [
      {
        id: Specs.ABJURATION,
        skills: [
          { name: 'speed control', level: 21, url: '/help/skin-control-speed-control-flight' },
          { name: 'flight control', level: 18, url: '/help/skin-control-speed-control-flight' },
          { name: 'skin control', level: 20, url: '/help/skin-control-speed-control-flight' },
          { name: 'phase control', level: 22, url: '/help/skin-control-speed-control-flight' },
        ],
      },
    ],
    magicMajorChoices: [
      {
        spec: Specs.ABJURATION,
        desc: [
          'Requires shapeshifting controls to maintain spells when shapeshifting',
        ],
      },
      {
        spec: Specs.ALTERATION,
        desc: [
          'Gain a major shapeshifting form at higher ranks',
          'Shapeshift without needing to use shape controls',
        ],
      },
    ],
  },

  [Class.INVOKER]: {
    name: Class.INVOKER,
    title: 'Invoker',
    slug: 'invoker',
    description: 'Specialist mages who are masters of energy manipulation.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.GOOD, Alignment.NEUTRAL, Alignment.EVIL],
    reference: [],
  },

  [Class.NECROMANCER]: {
    name: Class.NECROMANCER,
    title: 'Necromancer',
    slug: 'necromancer',
    description: 'Specialist mages who practice the black magics.',
    features: [],
    xpPenalty: 0,
    allowedAlignments: [Alignment.EVIL],
    reference: [],
  },

  [Class.OUTCAST]: {
    name: Class.OUTCAST,
    title: 'Outcast',
    slug: 'outcast',
    description:
      'Knight outcasts who turn on good and follow the black magics.',
    features: [],
    xpPenalty: 15,
    allowedAlignments: [Alignment.EVIL],
    reference: [],
  },
};

// Helper function to get class by name
export function getClass(name: Class | string): ClassData | undefined {
  return classes[name as Class];
}

// Helper function to get class by slug
export function getClassBySlug(slug: string): ClassData | undefined {
  return Object.values(classes).find(cls => cls.slug === slug);
}

// Helper function to get all classes
export function getAllClasses(): ClassData[] {
  return Object.values(classes);
}

// Helper function to get classes by alignment
export function getClassesByAlignment(alignment: Alignment): ClassData[] {
  return Object.values(classes).filter(cls =>
    cls.allowedAlignments.includes(alignment)
  );
}
